### ISSUE TITLE
Orçamento espaço kids

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#10]
Ver indicação com Maria Felipa

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by kim-soares** [comment]
Colocando aqui alguns fornecedores que encontrei para entrar em contato:
- https://www.organizandoeventos.com.br/karulinhasproducoes
- https://www.organizandoeventos.com.br/countryeventos
- https://www.organizandoeventos.com.br/vembricareventos
- https://www.organizandoeventos.com.br/carlakidsam.com.br
- https://www.instagram.com/kidsplay.salvador/

**Comment by kim-soares** [comment]
Pessoal, estou em contato com diversos fornecedores, mas para que eles possam passar um orçamento preciso das seguintes informações:
- Local do evento (entendo que ainda estamos em negociação com a UFBA - escola Politecnica, certo?)
- Data: 22 a 24 de setembro (confirmado?)
- Horário: 9h30 as 17h
- Área para o espaço kids: fechado/aberto? Se fechado qual altura do pé direito (convencional ou maior?)
- Estimativa de público: o evento está sendo pensado para 200 pessoas, é isso?

Acredito que só conseguiremos ter orçamentos reais (de todos os serviços) com essas informações confirmadas. Se alguém tiver um norte me avisa aqui!

**Comment by cecivieira** [comment]
Segem informações:

-     Local do evento: UFBA (Escola Politécnica)
-     Data: 22 a 24 de setembro
-     Horário: 9h30 as 17h (o espaço kids deve fechar as 18h)
-     Área para o espaço kids: sala de aula
-     Estimativa de público: para o espaço kids a estimatica são 10 crianças

O orçamento do Espaço Kids deve contar com a programação a ser realizada com as crianças e a quantidade de recreadores(as) disponíveis durante todo o dia. Também deve haver um controle da entrada e saída de crianças.

**Comment by kim-soares** [comment]
Orçamento da Brinquedos e Lanches Alegria

[-2023 Catálogo op BLA.pdf](https://github.com/pythonNordeste/organizacao-pyne-2023/files/11113772/-2023.Catalogo.op.BLA.pdf)

**Comment by kim-soares** [comment]
Catalogo SAMUEL DIVERSÕES LOCAÇÕES DE BRINQUEDOS:
Acesse este link para ver nosso catálogo no WhatsApp: https://wa.me/c/557182982500

**Comment by Lorenaps** [comment]
@lipemorais compartilhou o orçamento que ele realizou da empresa [Amora Brinquedos](https://www.instagram.com/amorabrinquedos/). Seria R$ 2.470 de 9 às 18 em um dia para crianças de 3 a 12 anos.
