### ISSUE TITLE
Preencher perguntas de perfil social no cadastro do Pretalks

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#100]
### Descrição

Os dados não serão usados na escolha de palestras. Só vão informar depois que forem avaliadas para saber o público que aplicou.

**Comment by maribedran** [comment]
@cecivieira depois manda as perguntas que tem na PyBR

**Comment by cecivieira** [comment]
Perguntas inseridas direto no pretalx
