### ISSUE TITLE
TecMundo

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#102]
https://www.linkedin.com/in/rodrigo-godoy-63226278/

**Comment by cecivieira** [comment]
1. realizado contato via linkedin
2. Rodirgo pediu plano de patrocinio
3. plano de patrocinio enviado via linkedin

**Comment by cecivieira** [comment]
Proposta da empresa:

"
Só pra eu contextualizar o meu gerente de marketing aqui
vocês tem abertura pra trabalhar com permuta?
porque aí poderíamos pensar em, por exemplo, dar visibilidade ao evento dentro do tecmundo com os nossos serviços de conteúdo. Desde produção de uma pauta falando sobre o evento, mídia display, post em rede social, menção em vídeo no youtube, temos vários formatos

Aí pelos valores eu vejo que provavelmente seria na cota ouro
"

**Comment by tiidadavena** [comment]
Eles topariam a cota Ouro independente da permuta? Caso parte do valor seja revertido em permuta, sugiro as seguintes contrapartidas:

- Cessão de itens para sorteio (licenças e/ou brindes diversos)
- Eles tem podcast? Se sim, chamar até 3 pessoas da organização para serem entrevistadas com o intuito de divulgar o evento, conscientizar sobre voluntariado
- Entrevista online com até 3 pessoas da org (vide item anterior) - [Exemplo do que rolou na PyBR 2021](https://www.youtube.com/watch?v=ulMcEUR2ODM&ab_channel=CastalioPodcast) - acho interessante mandar esse link para eles também
- Divulgação durante uma semana na newsletter The Brief
- 2 posts em cada rede social do Tecmundo - podemos ajudar na estruturação desse conteúdo
- Eles podem indicar outras empresas parceiras

**Comment by kim-soares** [comment]
A priori parece ser uma excelente contrapartida, por conta do tamanho do portal e seu volume de acessos. 

Mas pensando em conversão de leads, ou seja, ter mais pessoas inscritas no evento, eu acho que não vale a pena, a não ser que a base de leitores/acessos da TecMundo da região Nordeste seja expressivo.

**Comment by tiidadavena** [comment]
> A priori parece ser uma excelente contrapartida, por conta do tamanho do portal e seu volume de acessos.
> 
> Mas pensando em conversão de leads, ou seja, ter mais pessoas inscritas no evento, eu acho que não vale a pena, a não ser que a base de leitores/acessos da TecMundo da região Nordeste seja expressivo.

Acho super justo (e tranquilo) pedir essas infos da parte deles.

Sobre as contrapartidas, solicitar pelo menos 6 itens para sorteio (2 para cada dia de evento).

**Comment by cecivieira** [comment]
Vocês acreditam que propaganda na Tecmundo atrairá patrocinadoras?
Acredito que hoje nossa dificuldade é de atrair patrocinadoras, não público para comprar ingressos.

**Comment by kim-soares** [comment]
Acredito que pode ser uma porta sim. O lance é fazer o direcionamento do texto para esse foco. 

Gostei demais da ideia. Apostaria nessa parceria!

**Comment by cecivieira** [comment]
Nova mensagem da Tecmundo:

"
Tive uma reunião com o gerente de marketing há pouco e aproveitei o espaço pra falar sobre. Pra gente faz sentido a permuta sim se pra vocês também fizer. Aí a gente só teria alguns ajustes, porque pra nós não faz muito sentido os ingressos dado que a nossa sede é em Curitiba e os custos pra mandar as pessoas presencial não seriam muito interessantes e também não faz muito sentido termos um stand por não haver produto físico a ser mostrado. 
Do nosso lado o caminho mais interessante seria produzirmos dentro do TecMundo um conteúdo patrocinado mediante briefing que divulgue o evento de vocês, fazendo link de direcionamento pro site de compra e aí trabalhar inserções omnichannel nas redes sociais do TecMundo e podemos estudar uma call to action dentro de um vídeo no youtube também.

Hoje pra te dar uma dimensão o TecMundo recebe em média 19 milhões de visitas mensais e a Bahia é o nosso sexto maior nicho dentro do país
"

**Comment by maribedran** [comment]
Acho que o evento precisa de dinheiro, publico já tem. Inclusive vai faltar ingresso. Só se eles tiverem uma proposta de como criar conteúdo que vai converter em patrocinadores com um valor acima do que seria a cota ouro que a gente daria pra eles. Acho bem difícil esse conteúdo ter uma conversão dessas.

**Comment by cecivieira** [comment]
Perguntei a Rodrigo se ele acha que teríamos uma conversão para patrocinadoras. Segue a conversa:

"
 **Ana Cecília Vieira (She/Her) 5:29 PM**
Hoje nossa busca é por empresa patrocinadora. Você acredita que poderia produzir um conteúdo com foco em patrocinadoras em potencial para o evento?


**Rodrigo Godoy 5:32 PM**
Aí eu não acho que o TecMundo seja o caminho, mas dentro de casa nós temos o TheBrief. Conhece? 

Ele é uma newsletter com um volume expressivo de assinantes (mas claro que bem menor que a audiência do tecmundo) que é enviada diretamente as pessoas que se inscrevem. Essa base é bastante engajada e é composta em grande parte por pessoas em cargo de liderança em empresas de tecnologia. Conseguimos pensar em fazer uma inserção dentro de uma newsletter focada em falar com esse nicho também

Eu acredito que até temos cases referentes a isso, pode ser um caminho bem legal pra vocês

https://www.tecmundo.com.br/the-brief se quiser dar uma olhadinha

aqui tem uma de exemplo:

https://app.rdstation.email/mail/a7aa2c2d-1cf6-4276-94e6-806c0080ac03?utm_campaign=the_brief_newsletter_-_12_de_maio_de_2023&utm_medium=email&utm_source=RD+Station 
"

**Comment by felipythondev** [comment]
Acho que o foco está bem certinho. Focar marketing que converta em patrocinadores para o evento.

Pensando nisso vale, falar em todos os canais que eles tiverem disponíveis para que isso possa aumentar nossas chances da comunicação alcançar um patrocinador.
