### ISSUE TITLE
Avanade

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#103]
https://www.linkedin.com/in/beatriz-vannucci-pivotto/

**Comment by cecivieira** [comment]
realizado contato por linkedin

**Comment by cecivieira** [comment]
@kim-soares foi solicitado envio de plano de patrocínio por e-mail. Tu pode enviar?
Beatriz.pivotto@avanade.com

**Comment by kim-soares** [comment]
@cecivieira Feito
