### ISSUE TITLE
Orange Juice

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#107]
https://www.linkedin.com/in/beatriz-vannucci-pivotto/

**Comment by cecivieira** [comment]
Contato realizado via linkedin

**Comment by cecivieira** [comment]
@kim-soares tu poderia enviar o plano de patrocínio para mariana.mendanah@fcamara.com.br?

**Comment by kim-soares** [comment]
@cecivieira Enviei, porém deu erro:


Mensagem bloqueada
Sua mensagem foi bloqueada por mariana.mendanah@fcamara.com.br. Consulte os detalhes técnicos abaixo para mais informações.

A resposta do servidor remoto foi:
550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [[DM3NAM02FT038.eop-nam02.prod.protection.outlook.com](http://dm3nam02ft038.eop-nam02.prod.protection.outlook.com/) 2023-05-18T14:06:55.612Z 08DB5796C27D6C9E]
