### ISSUE TITLE
Conversar com as pessoas que visitaram o local e descobrir o que é essencial de infraestrutura para o evento acontecer(@jadefigueredo)

### ISSUE THREAD

**Issue by jadefigueredo** [pythonNordeste/organizacao-pyne-2023#109]

**Comment by jadefigueredo** [comment]
1. Local tem infraestrutura de caixa de som e microfones;
2. Não há infraestrutura para gravação e depende de uma equipe externa para fazer isso, tem que ser um serviço separados. O orçamento já realizado e precisa da confirmação de @fabiobj que entrou em contato com a equipe. Em relação a transmissão foi resolvido foi decidido que as palestras serão gravadas mas não haverá transmissão ao vivo, registrada na aqui (#95) 
4. O que precisa ser levado: pilhas, materiais de limpeza...
5. @Lorenaps vai colocar todas as informações na planilha e colocar numa issue na semana que vem.

**Comment by Lorenaps** [comment]
Os detalhamentos da infra essencial + decoração estão nesse [Documento Organização Espaço PyNE 2023](https://docs.google.com/presentation/d/19FQRarg4-aAqZxHKOmK8VsxxpQTFPAMyZDufsdSm0L0/edit#slide=id.p).
Os itens essencial são material de limpeza e apoio (pilhas e pilotos) e os cartazes básicos de localização (banheiro, elevador, oficina e palestra) - Eu estimo que para esses itens o valor de 500 reais seja suficiente.

A planilha de custos com relação aos itens essenciais e demais itens de decoração/serviços está sendo [atualizada aqui](https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=2143753829).

A atualização final dos materiais estará disponível na issue #112 até o dia 03/06. Mas já teremos uma visão geral na #113.
