### ISSUE TITLE
Divulgação - BotCity

### ISSUE THREAD

**Issue by felipythondev** [pythonNordeste/organizacao-pyne-2023#110]
Divulgação dos patrocínios da BotCity como patrocinadora Ouro

**Comment by felipythondev** [comment]
@pythonNordeste/comunicacao-2023

**Comment by ElisLages** [comment]
eles mandaram alguma logo, @lipemorais?

**Comment by felipythondev** [comment]
Ainda não @ElisLages , a @tiidadavena  recomendou usar esse formulário aqui que captura essa e outras informações para fazermos essas divulgações.
https://docs.google.com/forms/d/e/1FAIpQLSdM-bWCHH04a0S4AQg7TdmLVOBzQWJViVIvfqJ6P_RIqPEZ5Q/viewform?usp=sharing

**Comment by cecivieira** [comment]
@lipemorais  Tu poderia entrar em contato com a Bootcity e perguntar se ela conseguiu enviar as informações necessárias? Ainda não recebemos a logo marca das patrocinadoras, mas acredito que foi porque a google alterou algumas regras e o formulário estava impedido de aceitar novas respostas.
Fiz as correções e o formulário está funcionando.

**Comment by felipythondev** [comment]
Olha acredito que esse formulário nunca foi enviado para o pessoal da BotCity. Acho que a @ElisLages achou que eu iria mandar e eu achei que ela mandaria. Foi isso mesmo? 👀

**Comment by cecivieira** [comment]
@lipemorais foi sim
respondi a issue com os questionamentos da Botcity. Talvez dê pra enviar o formulário nas respostas

**Comment by cecivieira** [comment]
@lipemorais a Bootcity ainda não enviou as informações para divulgação

**Comment by felipythondev** [comment]
Solicitei aqui novamente.

**Comment by cecivieira** [comment]
A empresa ainda não enviou nenhum material para divulgar

**Comment by ElisLages** [comment]
Instagram: https://www.instagram.com/p/CwD_WZ7rv_d/
Twitter: https://twitter.com/PythonNordeste/status/1692301505926209551
Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7098067748978573312
