### ISSUE TITLE
[Reunião] Geral: 03/07

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#114]
# Reunião <Grupo de trabalho ou tema da reunião>

- Data: <! –– data ––>  
- Participantes:
  - Fábio (@fabiobj)
  - Mari (@maribedran)
  - Patrícia (@PatriciaSilvaRecife)
  - Elis (@ElisLages)
  - Juliana (@tiidadavena)
  - Lorena (@Lorenaps)

## Ata

- Lorena perguntou sobre o valor do serviço de designer já realizado para para o evento - precisamos colocar esse valor na planilha de custos
- Mari falou que precisa relembrar o pessoal para finalizar as avaliações, o ideal seria que cada avaliação recebesse 3 avaliações
- Lorena fez atualizações sobre as atividades do operacional que estão em #112 
- Sobre parceria de hotel/hospedagem, ficamos de recomendar bairros próximos e de fácil acesso [atividade]
- Fábio vai fechar a contratação do serviço de lanche - para isso precisamos verificar se podemos receber apenas um recibo ou se é necessária a emissao de nota fiscal
- Atualizar os custos pensando que as pessoas da organização vão pagar o ingresso, ver como diminuir um pouco o valor de R$ 140
- Temos 44 pessoas no grupo da organização e com a proximidade do evento precisamos entender melhor **quem?** está atuando **em que?** - Mari vai mandar mensagem no grupo para iniciar essa atualização
- Questões da última semana:
    - Pessoas com palestras aprovadas precisam pagar ingresso? 
        - Sim - Incluir na tratativa de email de confirmação se a pessoa não tiver condições de comprar o ingresso a organização irá assumir o valor
    - Vocês teriam interesse de realizar um sorteio de cupons de 2 meses de globoplay durante a Python Nordeste? 
        - Sim!

### Ações para serem realizadas

- [x] #119
- [x] #118
- [x] #120

**Comment by Lorenaps** [comment]
- Definição Keynotes
[Doc com sugestões iniciais](https://docs.google.com/document/d/1KGrfOEAN5YcNVxfOkuHhEGPzvVeQJQmlgnJojseFDFQ/edit)
- #112 
- Atualização [planilha de custo](https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=2143753829)

**Comment by Lorenaps** [comment]
Pessoas com palestras aprovadas precisam pagar ingresso?

**Comment by cecivieira** [comment]
Questionamento Globo

Vocês teriam interesse de realizar um sorteio de cupons de 2 meses de globoplay durante a Python Nordeste? Temos ofertado essa possibilidade para os nossos parceiros como uma forma de potencializar nossa participação nos eventos 😊

Compartilharíamos um link/qrcode de inscrição para divulgação por aí. O que acham?

**Comment by tiidadavena** [comment]
@Lorenaps cada pessoa da org tem direito a quantos votos para Keynote?

**Comment by Lorenaps** [comment]
não falamos sobre quantidade de votos, mas super vale indicar os nomes que você apoia e/ou trazer outras referencias
