### ISSUE TITLE
Abrir inscrições

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#115]
### Descrição
Abrir inscrições na plataforma Eventbrite, usando a conta e formulários dos anos anteriores.

### Requisitos para a atividade ser considerada como concluída

- Criar formulário;
- Estabelecer ticketes conforme valor definido em #113 
- Abrir issues de atas para divulgação para equipe de Comunicação

**Comment by Lorenaps** [comment]
- No formulário de inscrição precisamos adicionar a pergunta sobre intolerância alimentar
- Precisamos também dividir na plataforma a quantidade de ingressos (participantes, palestrantes, organização), combinamos de fechar essa divisão na reuniao do dia 10/07 #121

**Comment by cecivieira** [comment]
@Lorenaps poderemos dar vouche para as pessoas palestrantes e organização.

**Comment by felipythondev** [comment]
@cecivieira temos uma ideia de quando abrir a venda de ingressos?

**Comment by cecivieira** [comment]
#128 solicitação de capa para evento

**Comment by cecivieira** [comment]
https://www.eventbrite.com.br/e/python-nordeste-2023-tickets-685066200447

link para compra de ingresso

**Comment by cecivieira** [comment]
Capacidade do local: 200 pessoas

Ingressos para participantes:
220

Ingressos para convidadas:
40
    - 6 u. GAMMA;
    - 8 patrocinadoras (1 ingresso para cada patrocinadora: botcity, elastic, globo, vinta) (aqui tem folga de ingresso para caso hajam mais empresas)
    - 3 NNC (mesa de abertura)
    - 3 keynotes (Matheus, Any e Tarcízio)
    - 20 organização
