### ISSUE TITLE
Fechar a contratação do serviço de lanche

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#118]

**Comment by Lorenaps** [comment]
Informações de orçamento estão em #26

**Comment by cecivieira** [comment]
@Lorenaps @fabiobj povo lindo,
não tô tendo mais resposta de vocês sobre o orćamento do lanche. Então, segunda vou comećar a pegar indicaćão e fechar com uma empresa.

Caso eu deva seguir com a empresa que vocês tão negociando, me passem o contato até segunda (14 ago).

**Comment by cecivieira** [comment]
#26

**Comment by cecivieira** [comment]
@jadefigueredo 
4 coffee breaks para 250 pessoas cada coffee

**Comment by cecivieira** [comment]
https://www.instagram.com/acozinhadengodevo/

sugestão de Felipe

**Comment by jadefigueredo** [comment]
Oi gente, boa noite!
Email enviado para Gabriela, da cozinha dengo de vó, com cópia para @cecivieira e @Lorenaps, aguardando resposta!

Além disso, pedi indicação para a mãe de uma amiga que geralmente faz eventos na AMATRA e ela me indicou este aqui: https://www.instagram.com/bombomds/?hl=pt-br. Enviei mensagem de whatsapp pedindo um orçamento com as quantidades e informando que tbm preciso que inclua opções veganas / vegetarias e a pessoa que me atendeu disse que retorna amanhã. Se a conversa evoluir vou tentar puxar para o e-mail porque fiquei com pressa de ter resposta, por isso fiz um primeiro contato logo via whatsapp.

**Comment by jadefigueredo** [comment]
Hello Clã!
É o seguinte: vim detalhar aqui os ocorridos pra gente ficar a par em como está o andamento da negociação do lanche, consegui três orçamentos, passarei os detalhes na reunião, por fim, tô tentando fechar uma parceria com Gabriela (cozinha dengo de vó), dentro do nosso teto. Serão kits no lanche da manhã, com a parte das bebidas em self service (fora dos kits porque a gente não achou legal colocar suco de caixinha) e o lanche da tarde tb em self service, com os alimentos dispostos na mesa e as pessoas se servindo. Em contrapartida, de ter abaixado tanto o valor, Gabriella pediu que nós divulgássemos seu trabalho. Os detalhes serão enviados amanhã no e-mail, estou aguardando.
