### ISSUE TITLE
Criar site do evento

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#12]
- Forkar repositório do [ano anterior](https://github.com/pythonNordeste/pyne2022)
- Retirar animação
 - Adequar identidade visual
 - Landpage informando local e redes sociais

**Comment by maribedran** [comment]
O site do evento costuma ser uma cópia do ano anterior com algumas modificações. Cada um é uma repo aqui na organização.

**Comment by tiidadavena** [comment]
Segue link do Figma com a proposta da landing page na versão inicial de lançamento: https://www.figma.com/file/05ZOXCw9axpoEAgvyqOMfW/Prot%C3%B3tipo---Landing-de-Lan%C3%A7amento-(v1.0)?node-id=0%3A1&t=fXKpxSyA8vn2kWUe-1

**Comment by tiidadavena** [comment]
Nos parementos realizados nos dias 02/03 e 03/03 com @ElisLages e @ElisLages, foram realizadas as seguintes atividades:

- Setup do deploy no Netilfy
- Remoção de itens antigos
- Ajustes na responsividade
- Adição dos assets da nova identidade visual
- Estruturação do layout inicial
- Lançamento do site

**Comment by ElisLages** [comment]
Oi, gente :) Estamos trazendo a primeira versão do site. 
Por favor, olhem e tragam os seus feedbacks até o dia 09/03/2023, para que façamos os ajustes necessários. 
Site: https://2023.pythonnordeste.org/

**Comment by tiidadavena** [comment]
O site está configurado no [Netifliy](https://app.netlify.com) cada PR vai gerar um review app para que qualquer pessoa da organização possa dar feedbacks e verificar a versão antes de ser publicada a versão para produção. Os PRs podem ser acessados no repo do site: https://github.com/pythonNordeste/pyne2023

**Comment by arthurcarneiro** [comment]
Gente, boa noite.

O site está lindo. Gostei muito dessa versão inicial. Parabéns.

![image](https://user-images.githubusercontent.com/33362471/223287601-cfb84c2c-49a6-4933-9cb9-d5903cea2978.png)

Abri com o chrome e deu tudo bem, mas com o firefox percebi que ficou desse modo.

**Comment by anjinha-oliveira** [comment]
Gente, está muito bonito. De verdade! Parabeeens. 
Abri no Chrome e Microsoft Edge pc e ta tudo certo, nada quebrado <3

**Comment by Lorenaps** [comment]
Oi Galera! Parabéns demais pelo trabalho! Ficou lindo <3 

Vou listar os comentários abaixo para a avaliação de vocês:
- Ao abrir no firefox ficou do mesmo jeito que [Arthur falou aqui](https://github.com/pythonNordeste/organizacao-pyne-2023/issues/12#issuecomment-1457272003)
- Ao abrir no celular, o ```PyNE23 | Python Nordeste 2023 | Salvador - BA, Brasil | Em Setembro```
não ficou no rodapé da página. Não sei se era essa a intenção, mas pareceu um pouco desconfigurado.
![image](https://user-images.githubusercontent.com/9660774/224777306-6a9099e6-fa5e-4a45-9bcf-02bae8675ea7.png)
- Acho que seria interessante mudar o ícone do link para o Likedin pela logo da plataforma
![image](https://user-images.githubusercontent.com/9660774/224778053-9585f8b5-09dd-4b2b-b9a6-f77cc8ad78af.png)
- Acho que seria interessante também antes de divulgar o site, fazer as mudanças da foto de perfil de todas as redes sociais, para que elas passem todas a mesma identidade visual.

**Comment by ElisLages** [comment]
Obrigada, @arthurcarneiro, o firefox não estava assim, mas todas testamos e vimos, vamos corrigir isso :)
Obrigada, @anjinha-oliveira, ficamos felizes que gostaram <3 
Obrigada, @Lorenaps, vamos verificar isso do celular também, embora nos nossos não estejam aparecendo igual ao seu print, mas muito obrigada. E sim, vamos mudar o ícone sim, pedimos a Carol o modelinho e vamos substituir. Sim, agora que já temos a estética do site aprovada, vamos preparar todas as artes para serem atualizadas as redes e lançar o site :)

**Comment by tiidadavena** [comment]
Pessoal, agradecemos os feedbacks!
cc @Carine-Neris @ElisLages 

Segue versão atualizada do site após as observações de vocês: https://2023.pythonnordeste.org/

**Comment by kim-soares** [comment]
Bom dia pessoal, acessei o site e fiquei pensando se não seria legal ter mais informações. Assim o site vira a referência de conteúdo do evento - ao invés das pessoas consumirem apenas as pílulas de conteúdos nas redes.

O site da Python Brasil 2022 tá bem completão e acredito que pode ser uma excelente referência, podemos montar a estrutura do site, usando a mesma lógica. 

https://2022.pythonbrasil.org.br/

É possível?

**Comment by ElisLages** [comment]
Oi @kim-soares, sim é possível e sim também, existe essa pretensão de termos mais informações. Mas a parte de palestrantes e keynotes por exemplo, são informações que ainda não possuímos. São coisas que serão atualizadas a medida do que for chegando. 
Exemplo: O local exato ainda está passando por processo de assinaturas de contrato. Quando tudo estiver totalmente acertado, a gente inclui. 
Muito obrigada pelo feedback. 😊😊😊

**Comment by tiidadavena** [comment]
> Bom dia pessoal, acessei o site e fiquei pensando se não seria legal ter mais informações. Assim o site vira a referência de conteúdo do evento - ao invés das pessoas consumirem apenas as pílulas de conteúdos nas redes.
> 
> O site da Python Brasil 2022 tá bem completão e acredito que pode ser uma excelente referência, podemos montar a estrutura do site, usando a mesma lógica.
> 
> https://2022.pythonbrasil.org.br/
> 
> É possível?

Oi, @kim-soares uma comparação mais alinhada com o status da PyNE é o da PyBR deste ano: https://2023.pythonbrasil.org.br/, que nós tomamos como base para lançar as informações iniciais. 

É rotineiro o site do evento ser atualizado ao decorrer do ano até bem perto do evento, com a versão dita "final" próxima a uma data do evento.

**Comment by felipythondev** [comment]
@pythonNordeste/conteudo-2023 preciso de ajuda. Para solicitar o patrocínio da PSF, é necessário ter as instruções sobre covid no site e pelos menos a estrutura da grade do evento. Em quanto tempo isso pode ser feito para desbloquear a solicitação de patrocínio.

**Comment by felipythondev** [comment]
Qual que nova solicitação para o site deve ser criada uma issue.
