### ISSUE TITLE
Divulgação - Elastic

### ISSUE THREAD

**Issue by felipythondev** [pythonNordeste/organizacao-pyne-2023#122]
Divulgação dos patrocínios da Elastic como patrocinadora Ouro

**Comment by felipythondev** [comment]
Estamos aguardando o contrato para agendar o pagamento.

**Comment by cecivieira** [comment]
@lipemorais o contrato foi assinado?

**Comment by felipythondev** [comment]
Não foi assinado ainda. Mandei e-mail para a Gabi da elastic hoje. Semana passada ela disse que já tinha enviado a invoice para ser paga mas ainda não tive retorno sobre o contrato, e nem sobre data de pagamento.

**Comment by cecivieira** [comment]
contrato assinado.
aguardando envio do dinheiro

@lipemorais tu poderia enviar o formulário para coleta das informações para divulgação?

**Comment by felipythondev** [comment]
Compartilhei com a Elastic o formulário, mas só podemos divulgar depois que o dinheiro estiver na conta.

**Comment by cecivieira** [comment]
@ElisLages por favor, divulga a empresa como patrocinadora ouro. As informações já estão na planilha

https://docs.google.com/spreadsheets/d/1EfPf_xKD8nDpxNVhVhTOPq5MBEhv9fUD71tExAN16t4/edit#gid=1103660704

**Comment by cecivieira** [comment]
@lipemorais o cupom de desconto para a patrocinadora está aqui:
https://docs.google.com/spreadsheets/d/1I5WQ4SDQHBZqKh0hEhvKIdvOEhCF7ZOJ7JvaDKAwVu8/edit#gid=0

O desconto só é aplicado na categoria de ingresso "convidadas"

**Comment by felipythondev** [comment]
Aguardando receber o valor de patrocínio.

**Comment by felipythondev** [comment]
Valor recebido. Ingresso enviado.
