### ISSUE TITLE
Enviar convites de Keynotes

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#123]
### Descrição

Enviar email convidando as pessoas selecionadas para Keynote.

- Você é incrível, vem ser nossa Keynote
- Explicação do que é o evento
- Auxílio financeiro
- Confirme até X
- Pedir foto de divulgação, descrição e links para redes sociais

**Comment by felipythondev** [comment]
@maribedran ficou de enviar os convite para os keynotes essa semana
