### ISSUE TITLE
Apoio financeiro para caravanas

### ISSUE THREAD

**Issue by MarcusAldrey** [pythonNordeste/organizacao-pyne-2023#124]
Estruturar a caravana com saída de Feira de Santana.

- Verificar com o DA do curso de ECOMP da UEFS a quantidade de pessoas interessadas na caravana.
Fizemos contato com o DA solicitando a pesquisa de interesse. Aguardando retorno.

-

**Comment by cecivieira** [comment]
Estudantes da UFPI solicitou auxílio financeiro para caravana

**Comment by cecivieira** [comment]
Atualmente o evento não dispõe de recursos financeiros para custear ingresso total ou parcial para caravanas. Aguardar decisão da próxima reunião #137 ou auxílio da PSF #88 

Planilha financeira:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=431805148

**Comment by cecivieira** [comment]
Com o recebimento do patrocínio da PSF, é possível dar incentivo às caravanas em forma de desconto de R$40.

Dado 10 cupons de desconto para Universidade Estadual de Feira de Santana

**Comment by cecivieira** [comment]
Enviado e-mail para UFPI informando sobre incentivo para caravanas.
