### ISSUE TITLE
Tratativa de patrocinio <> Botcity

### ISSUE THREAD

**Issue by felipythondev** [pythonNordeste/organizacao-pyne-2023#125]

**Comment by cecivieira** [comment]
de: @lipemorais 

Perguntas da BotCity da reunião de hoje.

Pessoal, sobre o estande de patrocinadores.
Sabemo se terá tomada pra ligar notebook no estande?
Vai ter internet no evento ou vão ter que usar algo deles mesmo?

Eles estão esperando o resultado da submissão de palestras para comprar passagens para seus funcionários que tiverem palestras aprovadas. Perguntaram quando devem ter esse retorno.

Perguntaram também sobre o núero de pessoas no evento. Falei de:
Participantes: 200
Organização: 30
Palestrantes: 28

Tá certo isso?

**Comment by cecivieira** [comment]
Ministrante de atividades:
26 + mesa (acho que serão 3 pessoas na mesa)

@maribedran quantas pessoas serão na mesa de abertura? Quem vai mediar?

**Comment by cecivieira** [comment]
@lipemorais 

Tem tomada no local dos stands

O evento não tem internet

Vou verificar com Márcio se tem tomada aonde vai ficar o estande

estande = mesa + cadeira
A empresa é responsável por trazer material para decorar e cobrir a mesa

**Comment by cecivieira** [comment]
@lipemorais o cupom de desconto para a patrocinadora está aqui:
https://docs.google.com/spreadsheets/d/1I5WQ4SDQHBZqKh0hEhvKIdvOEhCF7ZOJ7JvaDKAwVu8/edit#gid=0

O desconto só é aplicado na categoria de ingresso "convidadas"

**Comment by felipythondev** [comment]
Enviado a patrocinadora.
