### ISSUE TITLE
Aviso de envío dos aceites

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#127]
### Peça/publicidade solicitada
Avisar que os emails de aceite das propostas foi enviado

### Data prevista para uso da arte
Imediato

### Quais informações devem aparecer na arte
Informar que o emails de aceite das propostas foram enviados e que a submetedora tem até dia 25 para confirmar a sua participação no evento.

### Quais formatos necessários
- [x] Quadrado
- [x ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x ] Redes sociais (twitter, facebook e instagram);
- [ x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by ElisLages** [comment]
Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7088252078740938752
Twitter: https://twitter.com/PythonNordeste/status/1682487249231912960
Instagram: https://www.instagram.com/p/Cu-QXVevP00/
