### ISSUE TITLE
Capa para Eventbrite

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#128]
Capa para página da venda de ingressos.
A capa deve ter 2160 x 1080px

Acredito que pode ser igual a das redes sociais, que estão na issue #48 . Eu só não consegui acessá-las para reutilizar.

**Comment by ElisLages** [comment]
Ciente! Providenciando.

**Comment by ElisLages** [comment]
Link: https://www.canva.com/design/DAFppiWLEuU/GcAxB03zpgKEz_F_Q53UzA/edit?utm_content=DAFppiWLEuU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
