### ISSUE TITLE
Criação do grupo CDC

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#13]
Mandar mensagem no grupo da Python Brasil para ver se alguém que virá tem interesse em estar no grupo CDC

**Comment by kim-soares** [comment]
Eu comentei (em algum lugar aqui no Git) que estou a disposição para fazer parte do CDC desse ano :)

**Comment by maribedran** [comment]
@kim-soares o CDC não pode ser composto por pessoas da organização porque tem um conflito de interesses. Quem vai organizar o grupo é @anicelysantos
