### ISSUE TITLE
Avaliar viabilidade da Algorave no pós-evento

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#130]
### Descrição

- Seria preciso um espaço com caixas de som e onde dê para fazer projeções nas paredes
- Articular com as pessoas envolvidas na Algorave BR

**Comment by cecivieira** [comment]
Contato realizado com [A Borracharia](https://instagram.com/aborracharia?igshid=MzRlODBiNWFlZA==) sobre disponibilização de local.

**Comment by cecivieira** [comment]
A Borracharia não responde aos contatos.
