### ISSUE TITLE
Avaliar orçamento de passagem e hospedagem para keynotes

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#131]
### Descrição

Tarcízio e Anicely não moram em Salvador e teríamos que cobrir a ida de ambos:

Tarcízio:
- Passagem de SP: R$777
- Duas diárias: R$404

Anicely:
- Passagem de Recife: R$446
- Duas diárias: R$404

Total: R$2031

**Comment by cecivieira** [comment]
Realizado
