### ISSUE TITLE
Arte para Copo

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#132]
Arte para copo que vai compor o kit da participante do evento.

Por mim, coloca só a logo, mas se quiser uma arte mais complexa, abri essa issue.

**Comment by ElisLages** [comment]
Pasta contendo os modelos solicitados: https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV

**Comment by cecivieira** [comment]
@ElisLages não encontrei o modelo de copo nessa pasta

**Comment by cecivieira** [comment]
qual dos dois modelos de copo?


![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/736c6c39-67ec-4173-b4e0-884b38fffc65)

**Comment by tiidadavena** [comment]
> qual dos dois modelos de copo?
> 
> ![image](https://user-images.githubusercontent.com/30605862/261632429-736c6c39-67ec-4173-b4e0-884b38fffc65.png)

O fosco vai conseguir passar melhor as cores vibrantes da logo

**Comment by ElisLages** [comment]
> qual dos dois modelos de copo?
> 
> ![image](https://user-images.githubusercontent.com/30605862/261632429-736c6c39-67ec-4173-b4e0-884b38fffc65.png)

concordo com Ju, o fosco vai deixar as cores da logo mais visíveis.

**Comment by PatriciaSilvaRecife** [comment]
O fosco. Fará uma combinação perfeita para as cores.

**Comment by jadefigueredo** [comment]
Fosco!

**Comment by cecivieira** [comment]
Votação encerraada

Escolha: copo branco
