### ISSUE TITLE
Arte para Crachá

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#133]
Arte para crachá da participante do evento.

Deve conter espaço em branco para escrever nome e pronomes

**Comment by cecivieira** [comment]
Deve conter as logos das patrocinadoras ouro e diamante

**Comment by ElisLages** [comment]
Pasta com os modelos criados: https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV

**Comment by cecivieira** [comment]
@ElisLages no crachá deve conter apenas as logos das patrocinadoras ouro e diamante. seria possível corrigir isso?

**Comment by ElisLages** [comment]
Ok, faremos as alterações

**Comment by ElisLages** [comment]
Feito!

**Comment by cecivieira** [comment]
@ElisLages por favor, coloca a logo das patrocinadoras diamantes:
Dengo de Vó e PSF

https://github.com/pythonNordeste/organizacao-pyne-2023/issues/163
e
https://wiki.python.org/psf/PSF%20Press%20Kit?action=AttachFile&do=get&target=psf-logo-narrow-256x84-alpha.png

**Comment by ElisLages** [comment]
Inseridas: https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV
