### ISSUE TITLE
Arte para camiseta

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#135]
Arte para camiseta.

Deve conter a logo da patrocinadora diamante

Artes:

- [x] Organização
- [x] Participante

**Comment by cecivieira** [comment]
Gosto desse posicionamento de arte, maaasss é só um pitaco. Faz como tocar no teu coração.

![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/96ddafd3-6d69-44c6-9363-17680948f25e)

**Comment by ElisLages** [comment]
Pasta contendo os modelos solicitados: https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV

**Comment by cecivieira** [comment]
@ElisLages na camisa deve conter apenas a logo da patrocinadora diamante
as artes enviadas contem a logo de todas as patrocinadoras. seria possível corrigir?

**Comment by ElisLages** [comment]
Ok, faremos as alterações.

**Comment by ElisLages** [comment]
Feito!

**Comment by cecivieira** [comment]
@ElisLages seria possível fazer uma camisa pro CDC?

**Comment by ElisLages** [comment]
Sim, @cecivieira
Com certeza

**Comment by cecivieira** [comment]
@ElisLages por favor, coloca a logo das patrocinadoras diamantes:
Dengo de Vó e PSF

#163
e
https://wiki.python.org/psf/PSF%20Press%20Kit?action=AttachFile&do=get&target=psf-logo-narrow-256x84-alpha.png

**Comment by cecivieira** [comment]
@ElisLages qual a estikmativa que Carol deu para inserir as logos da patrocinadoras na camisa?

A camisa do CDC é a azul ou amarela?
Se der, deixa na pasta apenas a que será usada

**Comment by ElisLages** [comment]
As artes foram atualizadas hoje, estão disponíveis neste link: https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV

A camisa do CDC será a azul. 
Já removi a proposta de camisa amarela da pasta.
