### ISSUE TITLE
Orçar apresentação cultural para abertura

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#136]
Orçar apresentação cultural para abertura do evento.
A apresentação ocorrerá no dia 22 de setembro entre 16h e 16h30

**Comment by cecivieira** [comment]
de: @Lorenaps 

Ta mapeado para o grupo mãos no couro, grupo de samba de terreiro, o mesmo que tocou na conf do afro python 

A priori ta previsto 500 reais

https://www.instagram.com/reel/Cu-dzkrpAVh/?igshid=MzRlODBiNWFlZA%3D%3D

**Comment by Lorenaps** [comment]
Entrei em contato com o grupo por telefone, e o orçamento final para 30 min de apresentação + 1 caixa de som auxiliar que é necessária para a apresentação do grupo ficou um total de R$ 700 reais.

Eles geram nota fiscal. 

Informei a equipe que estamos só aguardando a liberação da UFBA e confirmamos com eles por Whatsapp. Informei a ele que provavelmente Cecília entraria em contato visto que eu não tenho o aplicativo.

O valor já foi adicionado na planilha de custo e aparentemente temos condições de arcar.

**Comment by Lorenaps** [comment]
Falta liberação da UFBA, se vai ser na área interna (foyer no teatro) ou externa.

**Comment by cecivieira** [comment]
UFBA liberou o uso do foyer do auditório:

https://mail.google.com/mail/u/4/#search/%C3%B4nibus/QgrcJHsblRxkGFnbSjjnFXZhwbnzGfVDVHL

**Comment by cecivieira** [comment]
@Lorenaps como entro em contato para fechar a contratação do grupo cultural?

**Comment by cecivieira** [comment]
Contato realizado com Mãos no Couro para realização da contratação

**Comment by cecivieira** [comment]
Solicitada nota fiscal a Dainho

**Comment by cecivieira** [comment]
Dainho dará resposta até quarta que vem (23)
