### ISSUE TITLE
Geral: 31 jul. 2023

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#137]
# Reunião <Grupo de trabalho ou tema da reunião>

- Data: <! –– data ––>  
- Participantes:
  - Nome e Sobrenome (@Github ou E-mail)

## Ata

_Adicione os itens que foram discutidos durante a reunião._

- 

### Ações para serem realizadas

- [ ] Atividade (@responsável)
- [ ]

**Comment by cecivieira** [comment]
Organização compra a própria camisa e crachá?

Se sim, o valor é de R$50

**Comment by maribedran** [comment]
Desconto para caravanas.

Se o patrocínio da PSF entrar a gente teria condições de oferecer isso.

**Comment by cecivieira** [comment]
de: @maribedran 

Criei esse ponto de pauta pra reunião de segunda, mas não vou estar nela nem nas outras de agosto. Resumindo a questão: em alguma reunião estávamos discutindo orçamentos e valores de ingresso, concluimos que se entrar o patrocínio da PSF, a gente teria dinheiro suficiente pra dar um desconto no ingressso para caravanas, mas não fechamos nada. Esse email da caravana do Piauí fala de um grupo de 30 estudantes. Talvez valha perguntar pra eles como tá essa organização e se temos como auxiliar de alguma outra forma.

**Comment by cecivieira** [comment]
Sobre caravanas:

Temos R$2500 no orçamento para custear passagem e hospedagem de 2 pessoas keynotes.
Caso elas não sejam custeadas, esse valor pode ir para subsidiar ingressos para caravanas.
