### ISSUE TITLE
Arte para divulgação de venda de ingressos

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#138]
Arte para divulgar a venda de ingressos.

Seria legal umas 2 ou 3 artes diferentes (que pode ser só mudar a cor de fundo) para informar:

- abertura das vendas
- o evento tá chegando, adquira seu ingresso
- os ingressos estão acabando, corre

**Comment by cecivieira** [comment]
Há 3 tipos de ingressos:

inteira
meio
solidário - obrigatória doação de 1kg de alimento não perecível

**Comment by ElisLages** [comment]
@cecivieira https://www.canva.com/design/DAFpqAIU-kg/80OWERcUQRCXfk4QfmCnJw/edit?utm_content=DAFpqAIU-kg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

vamos produzir as outras duas, mas, se quiser já abrir, podemos usar essa pra lançar.

**Comment by cecivieira** [comment]
que lindoooooo

**Comment by cecivieira** [comment]
@ElisLages tu poderia divulgar nas redes sociais?

Link pra compra
https://www.eventbrite.com.br/e/python-nordeste-2023-tickets-685066200447

**Comment by ElisLages** [comment]
Feito!

Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7090069798574858240
Twitter: https://twitter.com/PythonNordeste/status/1684304882281373696
Instagram: https://www.instagram.com/p/CvLId1nvH2z/

**Comment by cecivieira** [comment]
@ElisLages tu poderia divulgar novamente a venda de ingresso?
talvez nos stories?
Vou colocar nos grupos de Telegram agora
