### ISSUE TITLE
Entrar em contato com secretaria municiap e/ou estadual de inclusão

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#139]
O evento terá intérprete de libras para a maior parte do conteúdo, então a ideia é entrar em contato com as secretarias para que elas façam a divulgação do evento junto à população surda.

**Comment by PatriciaSilvaRecife** [comment]
Bem, entrei em contato com Unidade da Pessoa Com Deficiência - UPCD, unidade responsável pela população surda e demais populações com deficiência da Prefeitura de Salvador. 
Falei com Adriana que é a interprete de LIBRAS e a mesma nos parabenizou pela iniciativa de ter um evento com interpretes, porém informou que não poderá ajudar na divulgação por ter apenas 2 interpretes responsável por todas as ações do município e que estão ocupados com as ações para o Dia Nacional de Luta da Pessoa com Deficiência que é o dia 21 setembro e que fazem atividades para todo o mês, além de  não ser uma ação promovida pela prefeitura. 

E, falou que é importante o interprete que estará no evento faça o vídeo de divulgação e seja vinculado as redes.
Ainda pontuou que  um surdo ou um interprete vendo a divulgação que o evento contatará com interpretes na linguagem de sinais, divulgarão entre eles.
