### ISSUE TITLE
Arte para Backdrop e banner

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#140]
- [ ] Arte para backdrop de 5m x 2m
- [ ] Arte para banners de 80 cm x 120 cm

Referencia do tamanho do backdrop em #96

**Comment by cecivieira** [comment]
Artes:
https://drive.google.com/drive/folders/1nEyJnkyVXmLwsly_wdFArpV7Jo50lmkV

**Comment by cecivieira** [comment]
@ElisLages seria possível inserir a logo da Jusbrasil no banner e backdrop?
patrocinadora bronze

**Comment by cecivieira** [comment]
@ElisLages deve ser aplicada proporcionalidade da marca no banner também.
Acho que Carol só aplicou no backdrop
