### ISSUE TITLE
Reunião Geral 07/08

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#141]
# Reunião Geral

- Data: <! –– data ––>  
- Participantes:
  - Nome e Sobrenome (@Github ou E-mail)

## Ata

_Adicione os itens que foram discutidos durante a reunião._

- 

### Ações para serem realizadas

- [ ] Atividade (@responsável)
- [ ]

**Comment by Lorenaps** [comment]
#137
#136

**Comment by cecivieira** [comment]
78 ingressos vendidos

**Comment by Lorenaps** [comment]
- Sobre patrocinio e primeiro happy hour
    - possibilidade de colocar uma caixa de sorteio com bolinhas coloridas
    - fazer duas possibilidades de happy na sexta: 1º na jus e segundo em bar aberto pra contemplar as pessoas que não foram sorteadas
 - Serviços fechados:
     - fotografia - R$ 2,500 - assinar contrato
     - filmagem - R$2,900 - assinar contrato
     - apresentação maos couro - R$ 700 - assinar contrato

**Comment by cecivieira** [comment]
dinehiro para subsidiar caravana:

não temos
