### ISSUE TITLE
Mesa de abertura do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#142]
Definir mesa de abertura.

Convidada: NNC

**Comment by cecivieira** [comment]
de: @maribedran 

Na mesa de abertura gostaríamos que  o NNC fosse representado por Juliana Oliveira e Taneska Cal.
Teriam outros convidados confirmados? E existe um tema central dessa mesa de abertura? Algum direcionamento de fala?
Ademais, gostaríamos de ver com vocês a possibilidade dos integrantes do NNC participarem do evento assistindo a essa mesa de abertura. Seria um momento de formação e networking para o grupo.

**Comment by cecivieira** [comment]
de: @Lorenaps 

Na mesa de abertura gostaríamos que  o NNC fosse representado por Juliana Oliveira e Taneska Cal.

- Teriam outros convidados confirmados? 

R: Estamos prevendo outros keynotes para os outros dias do evento, mas essa mesa de abertura é dedicada apenas para o NNC. 

- E existe um tema central dessa mesa de abertura? Algum direcionamento de fala?

R: Não temos um tema central definido. Mas esse ano o evento completa 10 anos de existência enfatizando e celebrando a cultura, inteligência e força do povo nordestino. Esse evento em Salvador visa reafirmar isso, o nosso orgulho do nordeste, a nossa força.

Acreditamos que isso tem tudo haver também com o evento Nzinga que vocês realizaram esse ano, onde falaram de vários temas atuais relacionados a tecnologia e ancestralidade.

Então se puder ser algo nessa dinâmica de reconhecimento e celebração de tudo que a nossa cultura e ancestralidade tem realizado na tecnologia (para alem dos diversos campos do conhecimento), já estaríamos mais do que contemplados. 

- Ademais, gostaríamos de ver com vocês a possibilidade dos integrantes do NNC participarem do evento assistindo a essa mesa de abertura. Seria um momento de formação e networking para o grupo.

R: Eu concordo demais! Acho que faz todo sentido e como nesa abertura pode ser que nem todas as pessoas estejam presentes acho que não haveria problema com a lotação do espaço

**Comment by cecivieira** [comment]
@maribedran como tá esse contato?
Tudo certinho?
Já tem foto e minibio para gente fazer a divulgação?

Tas precisando de ajuda?

**Comment by cecivieira** [comment]
Novo contato realizado com NNC.

Re solicitado dados para divulgação e informado que ajuda de custo será realizada atraves de reembolso.

**Comment by cecivieira** [comment]
Quem vai mediar essa mesa?

**Comment by cecivieira** [comment]
Foi permitido ao NNC convidar todo o grupo (em torno de 15 pessoas) para assistir a mesa. Essas pessoas terão cesso apenas ao 1. dia do evento, sem necessidade de credenciamento. Os seus nomes deverão ser enviados pelo NNC até o dia 15 de setembro

**Comment by cecivieira** [comment]
Solicitar a NNC lista com participantes e explicitar o registrado no comentário anterior + enviar 2 vouches para participantes da mesa

**Comment by cecivieira** [comment]
Não estamos mais comseguindo contatoc om a NNC.

@tiidadavena tu poderia comentar aqui qual é a tua ideia de alternativa para a mesa de abertura?

**Comment by tiidadavena** [comment]
> Não estamos mais comseguindo contatoc om a NNC.
> 
> @tiidadavena tu poderia comentar aqui qual é a tua ideia de alternativa para a mesa de abertura?

Seria convidar pessoas que fazem parte da comunidade que integram o [DiversiPy](https://github.com/diversipython) para uma roda de abertura sobre mercado de trabalho, a importância de construir times diversos e relatos sobre vivências profissionais e pessoais enquanto pessoa LGBTQIAP+  dentro da comunidade Python.

Outro ponto, é que várias pessoas desse grupo que estarão presentes no evento e que podem responder com certa disponbilidade sobre a mesa de abertura.

**Comment by tiidadavena** [comment]
> > Não estamos mais comseguindo contatoc om a NNC.
> > @tiidadavena tu poderia comentar aqui qual é a tua ideia de alternativa para a mesa de abertura?
> 
> Seria convidar pessoas que fazem parte da comunidade que integram o [DiversiPy](https://github.com/diversipython) para uma roda de abertura sobre mercado de trabalho, a importância de construir times diversos e relatos sobre vivências profissionais e pessoais enquanto pessoa LGBTQIAP+ dentro da comunidade Python.
> 
> Outro ponto, é que várias pessoas desse grupo que estarão presentes no evento e que podem responder com certa disponbilidade sobre a mesa de abertura.
 
Ademais, os presentes podem convidar pessoas a colaborar e dar ideias. Sugiro presença de uma pessoa da Afropython e das PyLadies sobre visões de outros representantes de corpos dissisdentes.

**Comment by cecivieira** [comment]
Yabás das Ciências: representações femininas do conhecimento ancestral e científico

Durante a mesa serão discutidas as interseções existentes entre as ciências, a ancestralidade e o diálogo com as redes de computação e outros meios de conhecimento, a partir da visão e experiências de três mulheres negras que encontram-se em diferentes níveis acadêmicos.

Jaqueline Anjos de Oliveira

Mulher negra; africana em diáspora; representante da liderança do grupo de pesquisa e extensão Negras e Negros na computação UFBA/USP, coordenadora do núcleo de pesquisa Negras e Negros na Computação UFBA/USP, e atualmente estudante da graduação em Ciências Sociais UFBA. Tem realizado estudos sobre  raça e racismo no contexto acadêmico;   inclusão digital;  e acesso à universidade e a permanência por parte dos estudantes negros.

Juliana Oliveira

Mulher negra, baiana, mestranda do Programa de Pós-Graduação em Ciência da Computação pelo Instituto de Computação da Universidade Federal da Bahia e bacharela em Sistemas de Informação também pela UFBA. Extensionista em Computação há 12 anos, com experiência em gestão, execução, avaliação e comunicação da extensão, atuando no Grupo de Pesquisa em Informática, Educação e Sociedade - ONDA DIGITAL, SPIDeLab (Semio-Participatory Interaction Design Research Laboratory), Grupo NEGRÉGORA - Negras e Negros na Computação (UFBA/USP). Atualmente é Diretora Geral do Projeto Meninas Digitais - Regional Bahia. Tem realizado estudos sobre participação de mulheres (cis e trans) na tecnologia, Design participativo, Software Livre, Inclusão Digital, Segurança Digital, Extensão Universitária e Raça e Diversidade na Computação.

Taneska Cal

Sou uma mulher cis preta periférica que nasceu e se criou em Salvador-BA. Mãe de Makini de 7 anos, amo ciências & tecnologia. Gosto de andar de bike. Doutoranda no Programa de Pós Graduação Ensino, História e Filosofia das Ciências da Faculdade de Educação da Universidade Federal da Bahia - UFBA. Mestra pelo mesmo programa. É licenciada em Física, Química e Ciências. Atuou por mais de 15 anos na docência das disciplinas Física e Química na educação básica. Atualmente, dedica-se às pesquisas nas áreas: algoritmos enviesados; ensino de ciências; ensino de física, formação de professores(nova BNCC) de ciências da natureza através projeto Amplia Ciências - CTSA por meio do acelerador de partículas Sirius; realiza o projeto As Yabás- Ciências https://www.yabasciencia.com.br/. Realiza divulgação científica, além do site, no canal do YouTube Café científico com a Preta Taneska Cal - YouTube e no instagram @taneska_santana Participa dos grupos de pesquisas: Diversidade e Criticidade nas Ciências Naturais (DICCINA) – UFBA, Grupo de Pesquisa e Extensão em Informática, Educação e Sociedade (ONDA DIGITAL) – UFBA e o , Laboratório de Educação STEAM MAKER-LESTEM.

**Comment by cecivieira** [comment]
@ElisLages por favor, faz arte pra divulgar a mesa. No comentário anterior tem os resumos e aqui tem as fotos

1 - foto
![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/221b31fa-f9c1-4ca8-88dc-a779ebd414c1)

2 - foto
![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/93540a08-5e36-411c-8c53-bd9ad7edba5a)

3 - foto
![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/06607165-4fd4-482d-982c-ccc3508a3b46)

**Comment by ElisLages** [comment]
Encaminhado para produção, @cecivieira

**Comment by cecivieira** [comment]
@ElisLages quando for divulgar a mesa de abertua, por favor, faz um post compartilhado com @nncufba no instagram
