### ISSUE TITLE
Estacionamento para ônibus da UFPI

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#146]
Caravanda da UFPI solicita alojamento para ônibus da universidade:

https://mail.google.com/mail/u/4/#sent/FMfcgzGtwVxjsFGqQxtGCCbFhCfrGnGf

**Comment by cecivieira** [comment]
UFBA informa que será possível estacionar o ônibus no campus Ondina. E que as informações devem ser enviadas 1 semana antes da chegada da caravana.

**Comment by cecivieira** [comment]
@jadefigueredo 

Pergunta quais as informacões do ônibus que Marcio precisa e como devem ser enviadas

se por e-mail para ele

e pergunta qual é o setor que o motorista do ônibus deve procurar quando chegar lá

**Comment by jadefigueredo** [comment]
Oi @cecivieira email enviado!
Fiquei preocupada onde o ônibus vai ser estacionado pra que a gente possa proporcionar o melhor acesso das pessoas até a escola politécnica, eu coloquei isso no e-mail.
Fiquei pensando ou no estacionamento perto da faculdade de comunicação que dá acesso a escadaria que sobe pra Poli ou perto do estacionamento onde saem os busufbas. Qual seria a proposta? que as pessoas subam a escada ou esperem o busufba? acho que seria interessante a gente pensar nisso para que as pessoas não fiquem meio perdidas, já que provavelmente não conhecem a estrutura da UFBA.

**Comment by cecivieira** [comment]
@jadefigueredo quando vem de excursão no ônibus da universidade, ele não fica circulando pela cidade. Ele só trás até a cidade do evento e depois leva embora. Não precisa se preocupar aonde ele ficará estacionado.

**Comment by cecivieira** [comment]
O deslocamento dentro da cidade durante o evento, é feito de qualquer outra forma, não com o ônibus da UFPI
(costuma ser assim)

**Comment by jadefigueredo** [comment]
@cecivieira Eu sei. Estou falando do acesso das pessoas do Campus Ondina até a Escola Politécnica mesmo, não através do onibus da UFPI, mas se possível do busufba já que todo mundo pode pegar, ou da própria escada da Poli. Me referi ao deslocamento dentro da própria universidade mesmo, que é meio confuso pra quem não tá acostumado.

**Comment by cecivieira** [comment]
Entendi!!!
Quando a UFPI responder com os dados, a gente vê se precisam desse
deslocamento.

Quais são os dados que precisa do ônibus?

**Comment by jadefigueredo** [comment]
> 

Tô aguardando a resposta oficial dele no e-mail, mas pelo que ele me falou pessoalmente seria só a placa mesmo. Talvez o modelo do ônibus, no mínimo.

**Comment by cecivieira** [comment]
Respondido o contato da caravana da UFPI. Informei que é possível estacionar e que precisaríamos de informações até 1 semana antes da chegada dela.
Estão esperando nosso retorno sobre as informações necessárias.

**Comment by jadefigueredo** [comment]
Informações solicitadas para o estacionamento: **Empresa e placa do veículo.**

**Comment by cecivieira** [comment]
Informação repassada para organizadora da excursão.
Ela informou que conseguiu contato direto com o setor responsável.
