### ISSUE TITLE
Comprar passagem para keynote Anicely

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#148]
### Descrição
Comprar passagem de Recife para Salvador na quinta no horário mais cedo disponível e volta no domingo à noite

**Comment by cecivieira** [comment]
Voo comprado e hospedagem reservada no Ibis Rio Vermelho.
O envio para a palestrante está agendada para quarta-feira, pois até lá o processo de pagamento já foi completado.
