### ISSUE TITLE
Pedir orçamento de Camisas

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#15]

**Comment by lipemorais** [comment]
Julian Rodrigues +55 71 9903-3760

**Comment by deboraos** [comment]
50 - 24,00

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0
