### ISSUE TITLE
Divulgação de keynote: Matheus Moreira

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#151]
### Campanha
Divulgação de keynote
  
### Peça/publicidade solicitada
Cientista de dados por profissão, pesquisador da Economia Política das Tecnologias de Informação e Comunicação e co-fundador do SoteroLab (não necessariamente nesta ordem).

![Matheus](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/252178/1a1f5a9c-1adb-4d73-ade7-0c9711e08d36)

### Detalhamento do uso
Instagram:  @matheus.msrs.

### Data prevista para uso da arte
*Informe a data ou período previsto para uso da arte*

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by maribedran** [comment]
@ElisLages depois adiciono o texto de apresentação. Mas vou deixar a issue aberta já.

**Comment by ElisLages** [comment]
Beleza, @maribedran
Obrigada :)
