### ISSUE TITLE
Novatec

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#158]
Recebido e-mail informando intenção de apoio da Novatec

**Comment by cecivieira** [comment]
@lipemorais a novatec mandou mensagem pedindo o contato da pessoa responsável pelo evento. Respondi informando que o contato pode ser realizado por e-mail e perguntando se tem alguma proposta. Além disso, enviei o plano de patrocínio.

Dar andamento ao contato, por favor, caso respondam.

**Comment by felipythondev** [comment]
Ok, vou dar uma olhada no e-mail e dar sequência na comunicação.
