### ISSUE TITLE
Dengo de Vó

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#163]
Como informado na #118 está sendo negociada parceria com a fornecedora dos lanches para que caiba no orçamento atual.

Com isso, foi ofertado para o Dengo de Vó a seguinte contrapartida:

-     Logo no banner;
-     Logo no site;
-     Postagem da logo da empresa nas nossas redes sociais;
-     Inserção de material promocional no kit das participantes (o material é fornecido por você);
-     Logo no telão, nas pausas entre atividades;
-     Logo na transmissão para o Youtube;
-     Logo no crachá;
-     01 mensagem por mail marketing para as participantes;
-     Logo na camiseta.

**Comment by cecivieira** [comment]
Contrato revisado
Enviados ajustes
Aguardando devolução de contrato ajustado

**Comment by jadefigueredo** [comment]
Contrato ajustado devolvido e assinado pelas partes.
Aguardando ajustes que serão enviados por email, como:
- especificação de desconto;
- logo da empresa em alta resolução.

**Comment by cecivieira** [comment]
![LOGO_DENGO](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/30605862/ac4260db-ad6e-41d9-a938-538269ee4f8f)

**Comment by tiidadavena** [comment]
Logo adicionada no site: https://pyne2023.onrender.com/

**Comment by jadefigueredo** [comment]
**_Cardápio_** 

**KIT CAFÉ DA MANHÃ PARA OS DIAS 23 E 24/09** 
- 200g Frutas Finas de Época; 2 unid. Pão Delícia Recheado; 
- 150g de Cuscuz Nordestino; 1 Sanduíche Natural; 
- 100gr Biscoitos Amanteigados/Recheados e 1 und Cupcake) ) 

**LANCHE DA TARDE** 
_dia 23/09_
- Salgados livres em coquetel com suco e refrigerante
_dia 24/09_ 
- abarás recheados; 
- vatapá + patê de camarão e pimenta livres em coquetel com sucos e refrigerantes;

**UTENSÍLIOS**

- 1000 unidades de copo descartáveis ;
- 500 unidades guardanapos ;
- 750 unidades colheres de sobremesa; 
- 750 unidades de mexedores de cafézinho; 
- 1000 unidades copinhos de café;
- 2 GARRAFAS TÉRMICAS DE 20 LITROS ; 
- 1 SUQUEIRA DE VIDRO 15 LITROS ; 
- 1 SUQUEIRA DE VIDRO 10 LITROS ; 
- 10 BANDEIJAS DE MDF; 
- 2 PANELAS MÉDIAS DE BARRO FINAS ; 
- 1 PANELA DE BARRO GRANDE FINA ; 
- 3 COLHERES DE PAU; 
- 2 JARROS DE BARRO.
