### ISSUE TITLE
Visita Técnica à Politécnica

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#167]
Itens para verificar na visita técnica aos espaços a serem usados durante a Python Nordeste na Escola Politécnica.

Comissão de visita:
@Lorenaps @jadefigueredo Leonardo
Luiza - Grupo de pesquisa GAMMA
Márcio - Diretoria da Politécnica

**Comment by cecivieira** [comment]
- [ ] Uso de equipamentos de som de todos os espaços;
- [ ] Uso de iluminação de todos os espaços (aonde ligar tudo e deixar as salas/auditórios funcionando completamente);
- [ ] Terá alguém da direção da politécnica de plantão para nos ajudar nos dias do evento?
- [ ] De onde poderemos pegar mesas e cadeiras para fazer stand das patrocinadoras? (2 mesas e 4 cadeiras)
- [ ] Sinalização do prédio (Exemplo: Auditório 1, Banheiro, Seta para chegar no auditório (quantas?).. Imagina que uma pessoa está entrando pela primeira vez no prédio e precisa chegar sozinha nos auditórios, sem precisar perguntar a ninguém. Quais sinalizações são necessárias para que ela tenha sucesso?)

**Comment by jadefigueredo** [comment]
- [ ] Quantidade de mesas e cadeiras para o coffeebrake;
- [ ] Espaços designados para estandes;
- [ ] Quantidade de tomadas;
- [ ] Quantidade de cabos para conexão: som, USB, extensões, etc. Precisaremos levar mais?
- [ ] Projetores disponíveis - quantos?
- [ ] Microfones

**Comment by leonardoleanodev** [comment]
## Auditórios teatros 
- 6o e 7o andar do lado direto

## Laboratórios para apresentações 5o e 6o andar do lado direito

LIAC: 5o Andar -> LIAC1 
- Sala de Aula: 6o Andar -> Departamento de Engenharia Quimica- > Sala de aula(no final do corredor)

## Espaço kids 7o andar
- Espaço kids: 7o andar -> a esquerda ao lado da biblioteca -> 7.3.7

## SALAS:
- Laboratório do 5o andar sala LABGRAD1 -15pc -  7:00 às 18:30 22 e 23

- LIAC1 - 15 pc - 7:00 às 18:30 22,23 e 24 

- LIDEO2 - 20 PC - 7:00 as 18:30 23 e 24

## informações sobre o uso dos equipamentos
- Procedimento para uso do equipamento de som na ordem:
-- Ligar os interruptores na caixa de som
-- Ligar o filtro de linha/ estabilizador
-- Ligar a caixa de potência para a mesa de som
-- Ligar a mesa de som
- Procedimento de desligamento dos equipamentos de som:
-- Fazer a ordem inversa do procedimento de ligar ligar
- Sobre iluminação:
-- A Iluminação dos auditórios está nas caixa de forca 

- Usuários disponíveis dos computadores:
-- Usuário das salas: './usuario'
-- Usuario da sala teatro auditório: './auditorio'

## Coisas a ressaltar
- Trazer por precausão por eventuais situações:
-- Mouse (o mouse do auditório não estava funcionando corretamente seria bom ter um stepe sem fio)
-- Baterias AA e palito para o funcionamento do ar condicionado e microfones sem fio (Levar pois a universidade não vai poder disponibilizar caso acabem as baterias)
-- Adaptadores de tomadas (tomadas do auditório estão todas no padrão antigo caso necessário precisaremos dos adaptadores)

## Coisas a Verificar
- Sexta-feira teremos apoio de funcionário para a parte technica no período da tarde, foi levantado a disponibilidade de um funcionário para o sábado e domingo mas não foi confirmado e nem o valor para termos essa disponibilidade

**Comment by Lorenaps** [comment]
## Sobre os Laboratórios

**Lab 1:**
Quantidade de máquinas: 15
Tem acesso a internet!

**Lab 2:**
Quantidade de máquinas: 20
Tem acesso a internet!

**Comment by leonardoleanodev** [comment]
Tive a devolutiva Marcio da passagem de som sao 120 reais o dia então 240 o final de semana para o evento

**Comment by cecivieira** [comment]
@LeonardoLeano333 a pessoa emite nota fiscal? a contratação precisa ser realizada com algum comprovante fiscal.
@Lorenaps lembro que você também falou a limpeza para o final de semana. Sabe quem está em contato com a pessoa? Seria @jade?

**Comment by jadefigueredo** [comment]
Olá, náo estou com o contato da pessoa responsável pela limpeza. Achei que esses dois contatos seriam realizados pelo @LeonardoLeano333, mas se ainda não foi feito posso entrar em contato.

**Comment by leonardoleanodev** [comment]
@cecivieira @jadefigueredo 
Mandei mensagem pra ele mas acho interessante a gente pensar se é possivel contornar, pois o Senhor que vai nos auxiliar é funcionário publico e não acho que ele tenha condições de emitir nota fiscal. De qualquer maneira estou aguardando a resposta dele
