### ISSUE TITLE
Pagar 2. parcela da hospedagem de keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#170]
Pagar 2. parcela da hospedagem de keynotes

**Comment by muriloviana** [comment]
Olá pessoal, tudo bem? Recebemos aqui na APyB a solicitação: Pagamento de Hospedagem de keynotes (Any e Tarcizio), parcela 1/2 para HOTELARIA ACCOR BRASIL S/A.

Porém o comprovante do pagamento não veio junto ao email. Sabem dizer se foi enviado? Se sim, deve ter sido bug no Ultradox (ferramenta usada para a solicitações junto à APyB), então vocês conseguiriam enviar novamente pra gente através do email diretoria@python.org.br.

Desculpa o transtorno 😅

**Comment by cecivieira** [comment]
Enviado @muriloviana
