### ISSUE TITLE
Organizar voluntariada para ser host em palestra

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#174]
Planilha para inserir nome das voluntárias que serão host em palestra e CDC

**Comment by Lorenaps** [comment]
Segue planilha https://docs.google.com/spreadsheets/d/1nx5Mgzpyxy7HpOdLo3BmfE9GQqrJB1RMLgb1BPdm4FU/edit#gid=0

**Comment by Lorenaps** [comment]
Planilha 
https://docs.google.com/spreadsheets/d/180UaYHOeTHGz13UnKa2i6jhqcxtC2iUlbDOKxilRKn8/edit#gid=880463512

**Comment by Lorenaps** [comment]
**Texto de Abertura:**


**Texto de Encerramento:**

**Comment by Lorenaps** [comment]
Aguardando recuperar os textos das edições passadas
