### ISSUE TITLE
Substituir palestra "Python além do Bacharelado: Expandindo horizontes e superando o desemprego"

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#178]
O palestrante informou que não poderá comparecer.
Precisa substituir na grade palestra "Python além do Bacharelado: Expandindo horizontes e superando o desemprego"

https://mail.google.com/mail/u/4/#inbox/FMfcgzGtwqNKgHhcDmmdZFskSTDBxGCV

**Comment by maribedran** [comment]
Palestra substituída: Como organizei minhas vida financeira com Python e você pode organizar a sua também
