### ISSUE TITLE
Divulgar Dengo de Vó : patrocinadora diamante

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#180]
Divulgar PSF : patrocinadora diamante
Redes sociais

**Comment by ElisLages** [comment]
Instagram: https://www.instagram.com/p/CxWd23grCxz/
Twitter/X: https://x.com/PythonNordeste/status/1703909335393275946?s=20
Linkedin: https://www.linkedin.com/posts/pythonnordeste_pythonnordeste-pyne2023-activity-7109673737687379968-YDLt?utm_source=share&utm_medium=member_desktop
