### ISSUE TITLE
Abertura das incrições em tutoriais

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#187]
### Campanha
Tutoriaus

### Peça/publicidade solicitada

Vamos abir hoje às 14:00 a incrição para tutoriais.

Você pode se inscrever pela plataforma da Eventbrite clicando em "Comprar ingressos" e selecionando os tutoriais na parte dos itens adicionais: https://www.eventbrite.com.br/e/python-nordeste-2023-tickets-685066200447

Para mais detalhes sobre o conteúdo das atividades, verifique a programação: https://pretalx.com/python-nordeste-2023/talk/

Corre que são poucas vagas!

### Detalhamento do uso
*Descreva em detalhe para que essa arte será usada, exemplo: arte para divulgação dos tipos das atividades do evento, deverá existir um cartão para cada tipo*

### Data prevista para uso da arte
Hoje, 19/09

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by ElisLages** [comment]
linkedin: https://www.linkedin.com/posts/pythonnordeste_pythonnordeste-pyne2023-activity-7110033610329464832-xYPj?utm_source=share&utm_medium=member_desktop
instagram: https://www.instagram.com/p/CxZCPWXLsZr/
twitter/X: https://x.com/PythonNordeste/status/1704269796353720490?s=20
