### ISSUE TITLE
Adicionar texto CDC no site

### ISSUE THREAD

**Issue by ElisLages** [pythonNordeste/organizacao-pyne-2023#188]
"Se ela pegou este texto da edição passada da python brasil, sim. Se não, ela precisa pegar de lá e colocar exatamente como está. Isto pq só podemos mudar qualquer  coisa depois da validação da comunidade e demora um pouco. 
Só preciso que mude ali onde tem pra entrar em contato colocando o link do formulário ao invés daquele email que está lá, pq eu não tenho acesso aquele email"

**Comment by tiidadavena** [comment]
Isso, o texto  foi fortemente baseado na PyBR 2022, adicionei o link para o forms de denúncia
