### ISSUE TITLE
Enviar identidade visual para fotógrafo 

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#190]
https://drive.google.com/drive/folders/1079b5nOnpgkQHxEWSXo4KuWBAqiwLH-b

From: fotógrafo
Criei essa pasta pra você upar tudo o que preciso pra colocar nos vídeos das palestras, me manda seu e-mail, vou liberar o acesso pra vc

**Comment by cecivieira** [comment]
@ElisLages envia o material que o fotógrafo precisa, por favor. Acho que é o #150 , mas pode ter mais
Tu poderia ver com ele?

Não teremos mais intérprete de libras.

**Comment by cecivieira** [comment]
Tem a capa de cada palestra também

**Comment by ElisLages** [comment]
> @ElisLages envia o material que o fotógrafo precisa, por favor. Acho que é o #150 , mas pode ter mais Tu poderia ver com ele?
> 
> Não teremos mais intérprete de libras.

A pasta com as artes da #150 estão aqui: https://www.canva.com/folder/FAFu69poAUE

**Comment by ElisLages** [comment]
Enviado!
