### ISSUE TITLE
Divulgar doação de alimentos

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#196]
Agradecer a todo mundo que doou alimentos e fez ser possível s fiscal de 105kg de alimento não perecível para essa entidade:
https://www.instagram.com/lar_recanto/

**Comment by ElisLages** [comment]
Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7115884274150445056
Instagram: https://www.instagram.com/p/CyCYlfVMdFH/
Twitter: https://x.com/PythonNordeste/status/1710090271499632926?s=20
