### ISSUE TITLE
Nota de repúdio

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#199]
Nota de repúdio #197

**Comment by cecivieira** [comment]
Essa nota só deverá ser publicada após revisão pela equipe do Cdc

**Comment by cecivieira** [comment]
Denúncia realizada para equipe do CDC #200 
Aguardando resposta para publicação da nota

**Comment by cecivieira** [comment]
@anicelysantos a equipe do CDC já teria alguma resposta sobre a denuncia?
Já poderíamos publicar a nota de repúdio que compartilhamos com vocês?

**Comment by anicelysantos** [comment]
@cecivieira em reunião, deliberamos que:

1. Vamos notificar a pessoa sobre a situação e a impedir de participar de eventos da comunidade a nível local, regional e nacional pelo período de 1 ano. 

2. Vamos notificar as comunidades relacionadas acima este bloqueio de participação desta pessoa.

No momento, estamos aguardando a ApyB indicar se temos apoio jurídico para resguardar esta decisão.

**Comment by cecivieira** [comment]
@anicelysantos a Equipe de Resposta do CDC da Python Nordeste tem apenas diligência sobre esse evento. O que se pode fazer é informar para as outras organizações e comunidades sobre o ocorrido.

Não existe um GT ou qualquer centralidade nas decisões junto a uma instituição que possa garantir a ação descrita no item 1.

As Equipes de Resposta ao CDC são criadas para vigência temporária e com escopo delimitado ao evento. Isso significa que as lideranças e membras da equipes mudam a cada novo evento, ainda que nos últimos 2 anos tenha sido convidada a mesma pessoa para liderança e essa repetido a equipe (o que pode ter dado a impressão de ter algo centralizado e com a abrangência nacional. Não tem! Esse assunto não avançou com a formação de GT, nem documentação e nem formalização.)

**Comment by anicelysantos** [comment]
Não, não deu a impressão. Só julguei que a equipe de resposta pudesse deliberar algo nesse sentido, dado a gravidade da situação.

Ainda não recebemos resposta em relação ao apoio jurídico, então se a organização quiser seguir em frente com a postagem da nota, tudo bem. Acho que só é o que dá pra fazer mesmo, diante da situação.

**Comment by cecivieira** [comment]
@anicelysantos tem um comentário no rascunho da nota de repúdio. Tu poderia verificar para fecharmos isso e publicar?
https://docs.google.com/document/d/15krxW7FWJXPSkxLxSuDF59KS21PF_jGGTzMYsT7GNfM/edit

**Comment by anicelysantos** [comment]
@cecivieira Feito!

**Comment by ElisLages** [comment]
Instagram: https://www.instagram.com/p/Cz9x-dcLP6l/?img_index=1
X: https://twitter.com/PythonNordeste/status/1727456568797511857
Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7133221355629465600/
