### ISSUE TITLE
Pesquisar possíveis locais

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#2]

**Comment by cecivieira** [comment]
ICBA

132 lugares - capacidade auditório icba
https://www.goethe.de/ins/br/pt/sta/sal/ser/mie.html

**Comment by moreira-matheus** [comment]
Unifacs - Campus Lapa
https://goo.gl/maps/xvExsjEJGnhtCSxY8

**Comment by gomex** [comment]
Qual nosso requisito para o local?

Normalmente eu vejo assim:

Quantas pessoas?
Precisa ser acessível (ex. rampas em caso de escadas e afins)
Perto de transporte público
Sistema de som próprio?
Quantas salas próximas pro evento?

**Comment by Lorenaps** [comment]
Pessoal, segue um email padrão para enviarmos para os respectivos contatos que possam nos ajudar a fechar o local: https://docs.google.com/document/d/1xOr2WjDNzEUfxVZaqPC0d2by5n0bml9WKUF02g9fI5o/edit?usp=sharing
