### ISSUE TITLE
Pedir orçamento de Intérpretes de Libras

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#20]

**Comment by lipemorais** [comment]
https://www.instagram.com/penseemlibras/

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by kim-soares** [comment]
Pessoal, segue orçamento do serviço de libras. Lembrando que esse orçamento não está 100% alinhado com o escopo do evento pois quando pedi faltavam informações.

Fiquei confuso sobre onde deveria compartilhar, por isso trouxe pra cá.

[Phyton Nordeste - orçamento - Cíntia Santos.pdf](https://github.com/pythonNordeste/organizacao-pyne-2023/files/11142063/Phyton.Nordeste.-.orcamento.-.Cintia.Santos.pdf)

**Comment by lipemorais** [comment]
A gente precisa saber como vai ficar a estrutura de conteúdo #42 para ter o orçamento final.

**Comment by cecivieira** [comment]
Solicitada revisão do orçamento para contratação

**Comment by cecivieira** [comment]
Orçamento:

https://drive.google.com/file/d/15WuUxESn_-O6N88UcIr3LOyvSuKTKd7e/view?usp=drive_link
