### ISSUE TITLE
Pedir orçamento de Equipe de gravação de palestra e transmissão ao vivo

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#21]

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by cecivieira** [comment]
Bloqueada pela #42

**Comment by Lorenaps** [comment]
Em uma oportunidade não planejada de contato com uma empresa que presta esse serviço, foi passado o orçamento de R$ 4.000,00 para os 3 dias de evento. Esse valor já está na planilha de custos (em #54).

**Comment by Lorenaps** [comment]
Ao tentar novo contato com o fornecedor para confirmar o orçamento de 4.000,00 para os 3 dias de evento, o valor foi alterado para 6 mil. E em reunião a equipe também achou que seria melhor priorizar os esforços para garantir um bom evento presencial ao invés de fazer transmissão.

Fica em aberto apenas ver alguma possibilidade de fazer pelos menos a filmagem das palestras keynotes.

**Comment by cecivieira** [comment]
@Lorenaps a partir da cota ouro, prometemos logo da empresa na transmissão. Então, talvez seja interessante gravar as palestras. Tu sabe se esse orçamento foi refeito apenas com a gravação e edição? Conversamos isso na reunião da semana passada.

@fabiobj tu conversou sobre isso com teu amigo?

**Comment by cecivieira** [comment]
@Lorenaps esse é o orçamento referente a gravação, certo?

Cobertura de todas as palestras - R$6.500,00

Cobertura 4 keynotes -  R$2.900,00
