### ISSUE TITLE
Pedir orçamento de Equipe de fotos

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#22]

**Comment by lipemorais** [comment]
Ingrid Suzarte  - +55 75 9109-0776

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by lipemorais** [comment]
A gente já sabe quantos dias serão de evento que vão precisar de fotografia?

**Comment by cecivieira** [comment]
O planejamento inicial é que o evento dure 3 dias: sexta, sábado e domingo

**Comment by lipemorais** [comment]
@pythonNordeste/operacional-2023 , alguém aqui pode entrar em contato com a fotógrafa ali?

**Comment by kim-soares** [comment]
Pessoal, a solicitação do orçamento deve ser para cobrir todo período do evento? De 8h as 18h? 
Tenho sugestão de fornecedor, posso ver com ele para levantar esse custo.

**Comment by maribedran** [comment]
@kim-soares te coloquei como responsável pela issu, tá?

**Comment by kim-soares** [comment]
@maribedran certinho mari, mas me confirma o horário do evento e a quantidade de dias, por favor!

**Comment by maribedran** [comment]
Seriam 3 dias, manhã e tarde. A grade não tá definida ainda, mas vê se isso é suficiente pra estimar o orçamento.

**Comment by LeonardoLeano333** [comment]
Pessoal estou vendo aqui sobre a Equipe de fotos, mas ainda não consegui o orçamento acredito que consiga o orçamento até o final dessa semana

**Comment by LeonardoLeano333** [comment]
pessoal atualizei a planilha com as informações de orçamento para equipe de fotografia

https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by cecivieira** [comment]
@kim-soares 

>Você tem verba estimada?
Não

>Quais as exigências?
Registrar atividades do evento e participantes

>Não livre fazendo o que tá acontecendo?
Não entendi a pergunta

>Tem backdrop?
O que é backdrop?

**Comment by Lorenaps** [comment]
> pessoal atualizei a planilha com as informações de orçamento para equipe de fotografia
> 
> https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

@LeonardoLeano333 muito obrigada! Tô tentando trazer outras opções pra gente ver o melhor preço que conseguimos. Assim que tivermos novidades te aviso!

**Comment by Lorenaps** [comment]
Ficou o melhor preço esse mesmo que você falou Leo!
