### ISSUE TITLE
Pedir orçamento de Lanches com opção vegana

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#26]

**Comment by lipemorais** [comment]
Monica, dona dos restaurantes Roma Negra e Malembe  +55 71 9379-1400

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by lipemorais** [comment]
Geisa Santos, sobre orçamentos de lanches, eu falei com a nana da NanaVeg e as VegsBaianas, porém, elas só podem me dar um orçamento pra a qtd de pessoas pós Yemanja

**Comment by lipemorais** [comment]
Yemanja é dia 02/Fev/2023

**Comment by Lorenaps** [comment]
Conseguimos o valor unitário do lanche, já com a entrega, por R$ 16 reais.

Existem algumas possibilidades para nossa escolha, a exemplo da disposição da comida: montagem de kits a ser entregue a cada pessoa ou mesa posta. Estamos conversando para tentar ao máximo fazer mesa posta sem encarecer o orçamento, pensando em como esse formato permite o diálogo entre as pessoas.

Pensando no coffee break da manhã (no sábado e domingo) como um café da manhã estamos em construção também de uma alimentação que possa dar uma revigorada no pessoal, como água de coco, algumas opções mais saudáveis e sempre inclusivas… (também sem encarecer o orçamento) - Um outro ponto sobre isso, para não perdermos de vista, é que teremos que coletar as restrições alimentares no ato da inscrição.

Por mim já podemos fechar com essa organização devido ao preço com a entrega e **principalmente** por toda experiência da equipe com as logisticas de alimentação com opções veganas.

**Comment by cecivieira** [comment]
@fabiobj @Lorenaps o valor de R$16 por pessoa permanece?
Qual é o contato para fechar a contratação?

**Comment by cecivieira** [comment]
Oláá
Qual valor que ficou do lanche?

**Comment by felipythondev** [comment]
https://www.instagram.com/acozinhadengodevo/
