### ISSUE TITLE
Pedir orçamento de Almoço com opção vegana

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#27]

**Comment by lipemorais** [comment]
Monica, dona dos restaurantes Roma Negra e Malembe  +55 71 9379-1400

**Comment by cecivieira** [comment]
Planilha para preencher valores do orçamento:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0

**Comment by lipemorais** [comment]
Geisa Santos: Sobre orçamentos de lanches, eu falei com a nana da NanaVeg e as VegsBaianas, porém, elas só podem me dar um orçamento pra a qtd de pessoas pós Yemanja, dia 02/Fev/2023

**Comment by Lorenaps** [comment]
Para almoço o orçamento fica no valor de R$ 25 por pessoa, com entrega.

Porém pensamos que essa pode ser uma opção selecionável no ato de inscrição, pois se o local final do evento for próximo a shopping ou local com muitas opções de almoço não vai fazer sentido incluírmos esse custo nas nossas previsões. 
Então hoje, ele já não entra na planilha de custos. Temos o orçamento e teremos até abril para decidirmos se colocamos o almoço como valor adicional e opcional na compra do ingresso.

Para decidir isso, precisamos:
- [ ] Verificar a estrutura de alimentação dos arredores do local do evento.
