### ISSUE TITLE
Redatar documento de apresentação do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#3]
Rascunho: https://docs.google.com/document/d/1WKd3h2iKzPaGX2-RhKqJIG0xGqGJg1f3fYkSof4bRz8/edit

**Comment by alynnefs** [comment]
isso vale pra versão online também? pelo que lembro, a gente tirou as informações pessoais do formulário de inscrição

**Comment by Lorenaps** [comment]
Temos uma primeira versão para avaliar pessoal, nela consta uma linha do tempo das edições/localidade. 
E salvo engano, ainda não tivemos uma edição em Alagoas. Talvez seja interessante desde já tentar o contato com a comunidade de lá, para que possa facilitar a passagem de conhecimento.

[Link da: PyNE 2023 - Apresentação inicial do evento](https://docs.google.com/document/d/1WKd3h2iKzPaGX2-RhKqJIG0xGqGJg1f3fYkSof4bRz8/edit#)
