### ISSUE TITLE
Criar identidade visual

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#30]
⚠️ Meu povo, temos até quarta feira (18/01) as 16 horas pra trazer comentários e ideias sobre a identidade visual. 

Tragam suas sugestões 🌻

Precisamos seguir esse prazo para a equipe de comunicação ter tempo hábil de avaliar as ideias e trazerem uma nova versão na próxima reunião que será dia 30/01, e nessa reunião batemos o martelo e colocamos o bloco na rua (quase...)

Simbora banda!

**Comment by cecivieira** [comment]
IMAGEM 1

![image](https://user-images.githubusercontent.com/30605862/212792743-d068e64b-29bd-4c9b-83a2-8eb3937c08c9.png)

**Comment by cecivieira** [comment]
imagem 2

![image](https://user-images.githubusercontent.com/30605862/212792801-917a55d8-9f77-41b2-8c90-74cead3a6539.png)

**Comment by cecivieira** [comment]
imagem 4

![image](https://user-images.githubusercontent.com/30605862/212792848-e06efef9-13cc-4410-83d7-dbb0927d8817.png)

**Comment by cecivieira** [comment]
imagem 4

![image](https://user-images.githubusercontent.com/30605862/212792903-acef16ac-db8b-4a0b-9526-7de411c3efdf.png)

**Comment by cecivieira** [comment]
Pitacos:

Imagem 1 - Amei a ideia das fitinhas, mas trocaria as cores do quadrado e logo do Python, pois me lembrou a AfroPython

Imagens 2, 3, 4 - Senti falta das fitinhas do Bonfim

**Comment by arthurcarneiro** [comment]
Pitacos:
Imagem 1 - Gostei muito das fitinhas, mas acho que há o que explorar mais também usando os quadrados. A silhueta de alguns dos monumentos da cidade. Além das cores que Cecília e Angela citaram.
Imagem 2, 3 e 4 - Eu acho que ficaria bem legal se conseguissemos inserir as fitinhas do Bonfim de uma forma clara. Além de que acho que poderiamos explorar também a estética das casas do Pelourinho, que remete bastante a Salvador.

**Comment by lipemorais** [comment]
Concordo com tudo que falaram. Nas imagens 2,3 e 4 parece que faltou espaço para o texto, e o "2023" ficou meio fininho e deformado comparado com o restante da fonte.

**Comment by Ryllari** [comment]
Sei que não estou na organização do evento mas como tenho acesso ao repo por estar na "organização" do GitHub acabei vendo essa thread e vim dar meus dois centavos de pitaco.

Amei os dois conceitos nas imagens. As fitinhas na primeira foi uma sacada muito massa e os monumentos nas últimas. Dito isso, _**não seria possível fazer um merge das duas?**_ Talvez manter a parte de baixo das últimas e inserir as fitinhas para tirar mais o branco? (A escolha de cores junto ao branco, me lembra muito a paleta da Google)

Outra coisa massa, em 2023 se completa 10 anos de Python Nordeste, vocês podem aproveitar isso também (Talvez um badge, não sei). Sei lá, querendo ou não se torna uma edição comemorativa, tendo em vista que foi o primeiro evento regional da comunidade Python no Brasil, essas coisas.

**Comment by lipemorais** [comment]
![Image](https://user-images.githubusercontent.com/5021565/215621530-3c97a1f4-0a43-4461-9bd1-b309da035d5b.png)

**Comment by tiidadavena** [comment]
Seguem as imagens da identidade visual pós-revisão para avaliação e feedbacks:
![image](https://user-images.githubusercontent.com/12106738/217106912-6d54a97e-f0fd-424d-b04d-a50b8aa4b8fc.png)
![image](https://user-images.githubusercontent.com/12106738/217106953-9aff75cd-6702-4731-9b6d-c69e77352304.png)
![image](https://user-images.githubusercontent.com/12106738/217106996-13aebf95-2d14-479c-b54d-30c2e9cde1b6.png)

**Comment by cecivieira** [comment]
Data limite para pitacos: 10 fev 2023

**Comment by Ryllari** [comment]
Dá pra usar a 1 e a 3 não? Tá difícil escolher só uma das duas <3
Acho que as duas podem ser utilizadas em aplicações diferentes, já que possuem características em comum.
**Exemplo de aplicação da Figura 1:** Ficaria muito boa pra um design de EcoBag, Chinela, Botton, caderno, faixa e se conseguir colocar efeito nessas fitinhas, ainda funciona pra VT em algum vídeo oficial ou transmissão.
**Exemplo de aplicação da Figura 2**: Ficaria muito boa para aviso, site, uso em e-mails ou comunicação, camiseta, também em faixas, cartazes, material de divulgação em geral, essas coisas.

Como a fitinha é virou um elemento presente nas duas imagens, ela também pode ser um elemento de conexão entre elas, tornando ambas parte da identidade visual do evento.

**Comment by cecivieira** [comment]
@ElisLages ambas as imagens compõe a mesma identidade visual, certo?

**Comment by arthurcarneiro** [comment]
Gostei bastante de ambas, imaginei a 1 ou a 2 compondo também algum recurso animado do site, uma troca de tela etc. Ou um fundo em marca d'água para a comunicação do evento. Como identidade do evento mesmo pensei a 3. As ideias de @Ryllari foram muito boas.

**Comment by ElisLages** [comment]
Sim, @cecivieira, ambas compõem a mesma identidade visual.

**Comment by cecivieira** [comment]
@ElisLages Massa!!!
Vou fechar a issue e abrir as primeiras demandas de arte pra gente atualizar as redes sociais.
