### ISSUE TITLE
Senai Cimatec para local do evento

### ISSUE THREAD

**Issue by lipemorais** [pythonNordeste/organizacao-pyne-2023#32]

**Comment by lipemorais** [comment]
Para o Senai Cimatec, @Lorenaps não está tendo resposta.

**Comment by arthurcarneiro** [comment]
Ultima atualização de @Lorenaps sobre Senai Cimatec: A equipe responsável por responder demorou bastante no retorno, e quando respondeu foi dizendo que não tinha disponibilidade no dia. Pedimos o orçamento para outras datas.

**Comment by arthurcarneiro** [comment]
Entrei em contato com o voluntariado do IEEE que estuda no Cimatec. Houve um comprometimento inicial de engajar o evento por lá e mencionaram a possibilidade de sediar o evento. Reunião dia 1/03 para alinharmos o convite e vermos isso. Acredito que algo concreto só será decidido na reunião geral do dia 06/03 #63.

**Comment by Lorenaps** [comment]
Ainda não houve resposta para o email solicitando novos orçamentos. Email foi enviado em 27/02.

**Comment by Lorenaps** [comment]
No email que foi enviado no dia 27, eu fiz a explicação e solicitação para dois eventos (python nordeste e afro python conf). Convidando o pessoal para uma reunião para falarmos sobre as possibilidades.

No dia 10/03 recebemos um retorno indicando a impossibilidade da realização, que as agendas estão comprometidas esse ano e que por isso são seria possível atender o evento afro python.

No dia 13/03 respondi o email perguntando sobre se a impossibilidade era para os dois eventos. Aguardando retorno.

**Comment by cecivieira** [comment]
Decidido o local pela UFBA #7
