### ISSUE TITLE
Itaú

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#38]
### Descrição
A empresa Unibanco entrou em contato demonstrando interesse em patrocinar o evento ([e-mail](https://mail.google.com/mail/u/4/?tab=om#inbox/FMfcgzGrcFgKLhtZmvMnLJcfPHszxjfh)).

### Requisitos para a atividade ser considerada como concluída

- Envio de plano de patrocínio
- Realizar contatos
- Definir sobre fechamento do contrato de patrocínio

**Comment by cecivieira** [comment]
Aguardando conclusão do plano de patrocínio para proceder envio.

**Comment by cecivieira** [comment]
@Lorenaps Posso enviar [esse documento de apresentação](https://docs.google.com/document/d/1WKd3h2iKzPaGX2-RhKqJIG0xGqGJg1f3fYkSof4bRz8/edit) para a Itaú? 

Informei no contato que ainda estamos trabalhando no Plano de Patrocínio , então solicitaram uma apresentação resumida do evento. Esse documento poderia ser usado para isso?

**Comment by cecivieira** [comment]
Enviada carta de apresentação

**Comment by lipemorais** [comment]
Não estão dando retorno.
