### ISSUE TITLE
Local para evento

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#40]
Como ainda não tivemos resposta de locais, temos que considerar buscar locais pagos.

---
### Descrição
Encontrar local para evento.

### Requisitos para a atividade ser considerada como concluída

- Buscar local
- Verificar disponibilidade de data
- Orçar
- Iniciar contratação

**Comment by Ryllari** [comment]
Vocês chegaram a ver o centro de convenções?
https://ccs-salvador.com.br

**Comment by cecivieira** [comment]
#7 #32

**Comment by cecivieira** [comment]
Ele é a Casa Rosa e cabe 450 no palco principal, segundo a pessoa que me mostrou, mas eu arriscaria dizer 350

"Ele é um local com apenas 1 palco então seria a possibilidade de fazer apenas 1 trilha mesmo, mas ele tem outros espaços interessantes

https://casarosasalvador.com.br/"

de: @Lorenaps

**Comment by cecivieira** [comment]
@Ryllari acredito que ainda não cogitamos. Vou entrar em contato essa semana

**Comment by cecivieira** [comment]
Solicitado orçamento a:
- [x] https://www.granhotelstellamaris.com.br
- [x] https://www.deville.com.br/hotel-deville-prime-salvador/eventos-hotel-deville-prime-salvador

**Comment by cecivieira** [comment]
Orçamento do [Hotel Deville prime](https://www.deville.com.br/hotel-deville-prime-salvador/eventos-hotel-deville-prime-salvador) - R$17.900 por dia

[orçamento](https://drive.google.com/file/d/13nzrrQswW9Y1WIuQ0PoIMphqasfYOopg/view?usp=share_link)

**Comment by Lorenaps** [comment]
Atualização dos últimos locais solicitados:

- UFBA (Escola Politécnica): Aguardando retorno. Prazo inicial de resposta 03/03, um novo email perguntando se havia alguma dúvida foi enviado nesse mesmo dia, ainda sem resposta. (#7 )
- [Casa Rosa](https://casarosasalvador.com.br/): Email foi respondido pela equipe da casa, reunião de apresentação foi marcada para 09/03 (quinta-feira) às 10 horas.
- Senai: Ainda sem retorno (#32 )

**Comment by Lorenaps** [comment]
### Sobre a reunião com a Casa Rosa na quinta 10/03

Conversamos sobre o espaço e as possibilidades de programação para fazer lá. Eles ficaram de nos mandar um orçamento.
Segue  alguns comentários abaixo:

- O local dispõe de 250 cadeiras + 60 banquinhos (já inclusos no aluguel)
- Para o [palco principal ](https://casarosasalvador.com.br/patio-viracao/) já existe uma caixa de som. Nos teriamos que providenciar os microfones e o operador de som. Caso a gente deseje usar a [sala rosa](https://casarosasalvador.com.br/sala-rosa/) para palestras também, teriamos que providenciar uma outra caixa de som e demais estruturas necessárias.
- Sobre o WIFI teríamos que providenciar um serviço extra, visto que a internet deles não pensada para o uso mais massivo como uma conferência;
- Se quisermos fazer oficinas lá, teremos que ou solicitar que o pessoal leve seu computador ou fazer o aluguel de computadores;
- Também devemos nos atentar que alguns espaços como a [Galeria/Foyer](https://casarosasalvador.com.br/galeria-foyer/) não deve ser utilizado para suportar estruturas pesadas como stands, pois o chão deve ser preservado.
- Existe uma plataforma elevadora para acesso da Sala Rosa, que fica no piso superior;

Por fim, minha opinião é que é um otimo local, ficaria um evento muito bonito lá, mas teríamos que fazer MUITAS adaptações para que ele pudesse comportar o formato da PyNE.

**Comment by cecivieira** [comment]
@Lorenaps as adaptações que precisaríamos fazer seriam as listadas no comentário anterior?

> - O local dispõe de 250 cadeiras + 60 banquinhos (já inclusos no aluguel)
> - Para o [palco principal ](https://casarosasalvador.com.br/patio-viracao/)já existe uma caixa de som. Nos teriamos que providenciar os microfones e o operador de som. Caso a gente deseje usar a [sala rosa](https://casarosasalvador.com.br/sala-rosa/) para palestras também, teriamos que providenciar uma outra caixa de som e demais estruturas necessárias.
> - Sobre o WIFI teríamos que providenciar um serviço extra, visto que a internet deles não pensada para o uso mais massivo como uma conferência;
> - Se quisermos fazer oficinas lá, teremos que ou solicitar que o pessoal leve seu computador ou fazer o aluguel de computadores;
> - Também devemos nos atentar que alguns espaços como a [Galeria/Foyer](https://casarosasalvador.com.br/galeria-foyer/) não deve ser utilizado para suportar estruturas pesadas como stands, pois o chão deve ser preservado.
> -  Existe uma plataforma elevadora para acesso da Sala Rosa, que fica no piso superior;

**Comment by cecivieira** [comment]
Continuação do contato com a UFBA:

' ' '
Prezada Lorena

Desculpe a demora pelo retorno, pois estávamos numa maratona de eventos aqui na escola. Seguem os encaminhamentos:

01 auditório para 200 pessoas - 6º andar - Reservado (você já deve até ter recebido o e-mail)

01 auditório para 80 pessoas - 6º andar - Reservado (você já deve até ter recebido o e-mail)

01 auditório para 35 pessoas  - 6º andar - Sala de apoio para a equipe de organização - Reservado (você já deve até ter recebido o e-mail)

Espaço para stands e coffee break: foyer dos auditórios  - 6º andar - Reservado (você já deve até ter recebido o e-mail)

Espaço para Open Space, 1 Sala para Espaço Kids - 02 salas de aula do sétimo andar (espaço kids na sala 7.3.7 e Open space na 7.3.6) - Pré-reserva - dependo da alocação do semestre 2023.2 para confirmar. Pode haver alteração da sala, mas teremos duas salas disponíveis.

Acessibilidade: auditórios tem rampa de acesso e 7º andar tem acesso por elevador

Laboratórios de informática: Pré-reserva de 02, podendo ampliar para 03 a depender das demandas de atividades da Escola no semestre 2023.2 - Pré-reserva de 2 Labs (você já deve até ter recebido o e-mail)

 

Questões-chave:

Sábado e domingo - Professora Karla e Grupo de pesquisa ficam responsáveis pela abertura, fechamento e desligamento dos equipamentos dos auditórios. Horário limite: 17 horas (reservei até 21h apenas por precaução)

Seguem termos de responsabilidade dos auditórios para preenchimento e assinatura

Por favor, me informe um contato telefônico para registrar junto às reservas.

' ' '

**Comment by Lorenaps** [comment]
> @Lorenaps as adaptações que precisaríamos fazer seriam as listadas no comentário anterior?
> 
> > * O local dispõe de 250 cadeiras + 60 banquinhos (já inclusos no aluguel)
> > * Para o [palco principal ](https://casarosasalvador.com.br/patio-viracao/)já existe uma caixa de som. Nos teriamos que providenciar os microfones e o operador de som. Caso a gente deseje usar a [sala rosa](https://casarosasalvador.com.br/sala-rosa/) para palestras também, teriamos que providenciar uma outra caixa de som e demais estruturas necessárias.
> > * Sobre o WIFI teríamos que providenciar um serviço extra, visto que a internet deles não pensada para o uso mais massivo como uma conferência;
> > * Se quisermos fazer oficinas lá, teremos que ou solicitar que o pessoal leve seu computador ou fazer o aluguel de computadores;
> > * Também devemos nos atentar que alguns espaços como a [Galeria/Foyer](https://casarosasalvador.com.br/galeria-foyer/) não deve ser utilizado para suportar estruturas pesadas como stands, pois o chão deve ser preservado.
> > * Existe uma plataforma elevadora para acesso da Sala Rosa, que fica no piso superior;

Sim

**Comment by Lorenaps** [comment]
Os termos de responsabilidade foram preenchidos por @leasampaio e por conta do feriado agendamos o email para amanhã (dia 10/04 as 7:50 da manhã), pelo email oficial do evento.

Além de passarmos as informações pedidas fazemos as solicitações:
- Logos para serem adicionadas no material do evento
- Data para visita dos espaços (para que possamos ter mais informações sobre infraestrturua, operacional e decoração)

**Comment by Lorenaps** [comment]
Tudo confirmado! As documentações foram aprovadas e visita aos espaços acontecerá no dia 26/04.

![image](https://user-images.githubusercontent.com/9660774/234147590-662aefc0-7fa4-4c25-bdcd-276503f2c366.png)
