### ISSUE TITLE
Criar repo do site

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#41]
- Forkar repositório do [ano anterior](https://github.com/pythonNordeste/pyne2022)
- Retirar animação
- Adequar identidade visual
- Landpage informando local e redes sociais

**Comment by cecivieira** [comment]
Issue duplicada #12

**Comment by tiidadavena** [comment]
Repo do site criado por @Carine-Neris: https://github.com/pythonNordeste/pyne2023
