### ISSUE TITLE
Pensar estrutura de conteúdo do evento

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#42]

**Comment by cecivieira** [comment]
@Fabiobj @deboraos @maribedran @ElisLages A gente consegue conversar hoje as 20h sobre a estrutura de conteúdo?

OU

sexta as 20h?

**Comment by cecivieira** [comment]
Estrutura:
https://docs.google.com/spreadsheets/d/1Crs_T_iqoLWPmWzt4CkNVGjZczZzyniTGc7vj9tzIU8/edit#gid=401476289

**Comment by Lorenaps** [comment]
Pessoal, adicionei uma sugestão de programação pensando nas caracteristicas e limitações do local com maior probabilidade de fechamento até agora. É apenas uma sugestão porque precisei pensar nessa esrtutura contando com os tutoriais para ter uma noção melhor para a previsão orçamentária. Segue no mesmo documento da sugestão inicial para que possamos avaliar. 
Tudo o que foi levado em consideração também está descrito na planilha:
https://docs.google.com/spreadsheets/d/1Crs_T_iqoLWPmWzt4CkNVGjZczZzyniTGc7vj9tzIU8/edit#gid=1906503563

**Comment by Lorenaps** [comment]
Pessoal, segue um documento onde anotei algumas ideias para a programação do evento, porém pensando mais na nossa intenção com ele, como a promoção da cultura da nossa região..., e ações de acessibilidade socioeconômica: https://docs.google.com/document/d/1KGrfOEAN5YcNVxfOkuHhEGPzvVeQJQmlgnJojseFDFQ/edit

**Comment by cecivieira** [comment]
Programação:
https://docs.google.com/spreadsheets/d/1Crs_T_iqoLWPmWzt4CkNVGjZczZzyniTGc7vj9tzIU8/edit#gid=1906503563

**Comment by Lorenaps** [comment]
Essa issue foi finalizada a partir da definição de [estrutura homologada](https://docs.google.com/spreadsheets/d/1Crs_T_iqoLWPmWzt4CkNVGjZczZzyniTGc7vj9tzIU8/edit#gid=1906503563) pela equipe em maio.
