### ISSUE TITLE
Orçar Centro de Convenções de Salvador

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#45]
### Descrição
Orçar Centro de Convenções de Salvador para setembro com requisitos descritos em #33 

### Requisitos para a atividade ser considerada como concluída

- Entrar em contato com Centro de Convenções
- Verificar estrutura
- Verificar agenda disponível
- Solicitar orçamento

**Comment by cecivieira** [comment]
Issue relacionada #40

**Comment by cecivieira** [comment]
@Ryllari criei essa issue para pegar orçamento do centro de convenções. Enviei o e-mail inicial com a carta de apresentação do evento, a partir do email nordeste@python.org. Tu pode pegar essa atividade?

Se sim, tu ainda tem acesso ao e-mail?

**Comment by cecivieira** [comment]
https://ccs-salvador.com.br/organizador/espaco-para-eventos/

**Comment by Ryllari** [comment]
Perdi o acesso ao e-mail. Mas posso pegar essa atividade sim.

**Comment by Ryllari** [comment]
Falei com o Victor, do centro de convenções.
Ele ficou de responder ao e-mail com possíveis datas e espaços que estariam disponíveis.
Questionou a possibilidade do evento ser no último fim de semana de agosto. Disse a ele que veria com vocês quanto a isso. 
Caso não role em setembro, acham possível jogar pra o último fim de semana de agosto?

Outra coisa:
Dei uma cantada nele, pra que fosse possível o centro de convenções solicitar um valor "simbólico" ou fornecer um grande desconto e converte-los de fornecedor para apoio ou patrocínio.

**Comment by Ryllari** [comment]
Eles me questionaram se tínhamos um budget previsto pra locação de espaço. Para eles fornecerem um orçamento que se adequasse a isso e não ser algo mega caro.

**Comment by Ryllari** [comment]
Eles sugeriram a última semana de setembro também, pegando o 01/Outubro.
Seria viável?
Vi em uma das atas que poderia ser o penúltimo fim de semana de setembro ou uma semana antes ou depois, mas achei melhor perguntar novamente porque vi outros contatos pedindo pra primeira semana de setembro.

**Comment by Ryllari** [comment]
Mapa dos espaços:
https://drive.google.com/drive/folders/1nO1YwwN-GsMkeL_4L1LOA1tyjqxxVG_d

**Comment by Lorenaps** [comment]
Maravilha @Ryllari! Com relação as datas eu acho que adiantar para o final de agosto é arriscado porque "perdemos 1 mês" de tempo pra conseguir fazer as coisas. Mas não vejo problema em postergar 1 semana passando para 29/09 até 01/10. 

Minha sugestão é que podemos sim confirmar essa possibilidade de postergar em 1 semana para que possamos conseguir o orçamento e quando tivermos o orçamento em mãos deliberamos com o pessoal se fechamos com esse local nessa data e as consequências dessa mudança de data para as outras atividades.

**Comment by Lorenaps** [comment]
Com relação ao budget, eu não tenho exatidão em informar. Arrisco que dizer que um valor "viável" para conseguirmos em patrocinio para o local seria 5 mil reais. Digo isso porque ainda temos outros custos também urgentes com os quais estaremos contando com o patrocínio.

**Comment by ElisLages** [comment]
Concordo com Lorena. 
Se precisamos alterar a data, é melhor que fique para o último fim de semana de setembro.

**Comment by cecivieira** [comment]
Decidido o local pela UFBA #7
