### ISSUE TITLE
Campanhas publicitárias

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#46]
### Descrição
Planejar a comunicação do evento: estabelecer campanhas publicitárias, peças de cada uma e data prevista para comunicação.
[Planejamento](https://docs.google.com/spreadsheets/d/14agAkGYBNqhCxnyXU0eJt8r8LHgLVcxcfdDJureCafY/edit#gid=0)

### Requisitos para a atividade ser considerada como concluída

- Definir campanhas
- Definir artes
- Abrir issues com as artes a serem solicitadas para a designer

**Comment by cecivieira** [comment]
@ElisLages terminei de revisar o planejamento. Queres fazer algum momento sincrono para fechar e enviar demanda pra designer?

**Comment by cecivieira** [comment]
@ElisLages @Carine-Neris quando vocês terminarem de revisar o planejamento, fecha essa issue, por favor. Se facilitar para vocês, abre uma issue pra cada template de arte ou divulgação.

Vou abrir as relacionadas a campanha "ponta pé inicial" pra gente começar a atualizar as redes sociais.

**Comment by Lorenaps** [comment]
Identidade visual da escola politecnica: http://www.eng.ufba.br/identidade-visual

**Comment by kim-soares** [comment]
@cecivieira temos previsão de entrega desses materiais?

**Comment by kim-soares** [comment]
@cecivieira você deletou a segunda aba na planilha? Eu tinha organizado em ordem cronológica pra ficar mais fácil de entender quando cada post deveria ir pro ar.

**Comment by cecivieira** [comment]
@kim-soares tinha apagado. Acabei de passar a modificação para a tabela inicial, assim não ficamos com 2 tabelas semelhantes. Ficou massa a sugestão de ordenação.
