### ISSUE TITLE
Imagem para perfil de redes sociais (facebook, instagram, twitter, linkedin)

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#48]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Imagem para perfil de redes sociais (facebook, instagram, twitter, linkedin)

### Detalhamento do uso
Redes sociais do evento

### Data prevista para uso da arte
01 março 23

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by ElisLages** [comment]
Icons para redes sociais: https://www.canva.com/folder/FAFdfSqafUc

**Comment by cecivieira** [comment]
Solicitado a @alynnefs as credenciais para login nas redes sociais da python nordeste

**Comment by cecivieira** [comment]
Atualizada as imagens de perfis do Twitter e Instagram.
Aguardando informações sobre existência de páginas no Linkedin e Facebook

**Comment by ElisLages** [comment]
Capa Twitter: https://www.canva.com/folder/FAFdfRaiLZg
Capa Linkedin: https://www.canva.com/folder/FAFfLC7XEkQ
Capa Facebook: https://www.canva.com/folder/FAFdfS0yjWI

**Comment by cecivieira** [comment]
perfis atualizados
