### ISSUE TITLE
Template para stories

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#49]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Template para publicação de informações nos stories do Instagram.  

### Detalhamento do uso
A peça seria apenas um template sem nenhuma informação, apenas a identidade visual e bastante espaço para que a organização possa escrever avisos.

### Data prevista para uso da arte
15 março 2023

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [ ] Quadrado
- [x] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by kim-soares** [comment]
Temos previsão de entrega desse material?

**Comment by ElisLages** [comment]
Template para Stories: https://www.canva.com/folder/FAFdfTp5Nu4
