### ISSUE TITLE
Listar e entrar em contato com possíveis patrocinadores

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#5]
https://docs.google.com/spreadsheets/d/12HfXQZ6NpnGjs3OJnrLiyNvc1v5PRoR_HcB_m30QBv0/edit?usp=sharing

**Comment by lipemorais** [comment]
@maribedran solicitei acesso a lista. 🙏🏿

**Comment by cecivieira** [comment]
@lipemorais liberei teu acesso

**Comment by kim-soares** [comment]
Estou entrando em contato com a algumas pessoas para nos ajudar a achar as pessoas certas para entrarmos em contato. Caso eu consiga avançar nisso vou atualizando aqui.

**Comment by kim-soares** [comment]
@lipemorais adicionei na planilha os dados de um contato no GitHub, se puder manda email para eles com o plano de patrocinio e todas as informações do evento, beleza?!

**Comment by kim-soares** [comment]
@cecivieira essa planilha aqui!

**Comment by cecivieira** [comment]
@kim-soares eu deveria entrar em contato com todas as pessoas que o campo "Responsável da organização" está em branco, correto?

Pensei em entrar em contato e depois direcionar para o e-mail pra tu seguir. O que tu acha?

**Comment by kim-soares** [comment]
Pode ser @cecivieira dessa forma que vc sugeriu!

**Comment by cecivieira** [comment]
@kim-soares contatos realizados via linkedin
