### ISSUE TITLE
Template para patrocinadores (Apoio, Bronze, Prata, Ouro)

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#52]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Template para divulgar empresas patrocinadoras e apoiadoras

### Detalhamento do uso
Deve ser 1 template para cada categoria: Apoio, Bronze, Prata, Ouro
O template deve ter espaço para logo da empresa

### Data prevista para uso da arte
abril 2023

### Quais informações devem aparecer na arte
Categoria de patrocínio

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by ddevdan** [comment]
Oii @cecivieira, eu criei esse template  para patrocinadores da pyne22 no figma. [aqui](https://www.figma.com/file/GxOkGF6RpxpGqDqWRbhFgS/template-divulga%C3%A7%C3%A3o-patrocinador-pyne22?node-id=0%3A1&t=YPE27ey98vhrv19K-0)

Talvez seja útil pra pyne23. Acho que dá pra aplicar alguns elementos visuais a identidade visual da pyne23

**Comment by cecivieira** [comment]
Cópia do template do ano passado, aonde @lipemorais tá atrualizanod as informações

https://www.canva.com/design/DAFYbRqxCAc/RzXEhovJ1WrOEzg0u3VlcQ/edit?utm_content=DAFYbRqxCAc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by cecivieira** [comment]
@ddevdan será que daria pra trazer o que tu fez para esse Canva do comentário anterior?

O Canva é mais fácil de mexer por nós, pessoas que não habilidosas em arte.

**Comment by cecivieira** [comment]
O template criado nessa issuse será usada na #14

**Comment by cecivieira** [comment]
@ElisLages Dan fez uma proposta. Vê se faz sentido ou ajuda a designer.
