### ISSUE TITLE
Assinatura de e-mail

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#53]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Assinatura para Gmail

### Detalhamento do uso
inserir como rodapé padrão para os e-mails

### Data prevista para uso da arte
Imediata

### Quais informações devem aparecer na arte
Título do evento, ano, local, @ das redes sociais

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *assinatura gmail*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by ElisLages** [comment]
![assinatura-de-email-pyNE2023](https://user-images.githubusercontent.com/69424151/218602008-27db6b02-b2b0-45b6-a2cc-dbd6c2fcd56c.png)

**Comment by cecivieira** [comment]
@ElisLages Sucesso demais! Só precisa tirar o endereço porque ele pode confundir a leitora no sentido de passar a mensagem de um endereço fiscal. A palavra "Salvador" na imagem já é suficiente pra informar aonde ocorrerá o evento.

**Comment by ElisLages** [comment]
@cecivieira Beleza!

**Comment by ElisLages** [comment]
![assinatura-de-email-pyNE2023 2](https://user-images.githubusercontent.com/69424151/218878617-f0c56dad-e075-4911-beb5-9267eae994b6.png)

OU

![assinatura-de-email-pyNE2023 3](https://user-images.githubusercontent.com/69424151/218878650-d41fbc78-32df-4b0b-9a30-c4c7f7dbb883.png)


@cecivieira
