### ISSUE TITLE
Previsão orçamentária

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#54]
### Descrição
Realizar previsão orçamentária do evento.

### Requisitos para a atividade ser considerada como concluída
- Listar previsão de custo de todos os itens necessários para aquisição (produtos e serviços)

**Comment by cecivieira** [comment]
Planilha:
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=722383328

**Comment by cecivieira** [comment]
Atualizar a planilha de custos com o desconto da plataforma de inscrição e com os orçamentos dos coffee-breaks 
Atividade tirada em: #54

**Comment by Lorenaps** [comment]
Olá pessoal!
Planilha de custos foi atualizada! Agora ela contempla:
- [ ] Orçamento dos custos urgentes (kit + alimentação)
- [ ] Cenários de custos (com almoço e lanche, com lanche, com valor parcial do lanche)
- [ ] Modalidades de ingresso (meia e inteira) para cada cenário descrito acima
- [ ] Previsão de Vendas X Custos, indicando o valor total disponível em caixa e como ele pagaria os custos urgentes
- [ ] A partir da previsão acima, uma estimativa das nossas metas de patrocínio

[Planilha está disponível no mesmo link enviado anteriormente](https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=722383328), na aba **Custos do Evento**

**Comment by Lorenaps** [comment]
A partir do cenário **Custos unitários com Lanche e sem Almoço** farei um descritivo para pleitear a isenção de aluguel  do espaço (enquanto um evento externo) junto a UFBA. 

A ideia desse descritivo é evidenciar pra eles que o evento é sem fins lucrativos e o valor da inscrição é apenas para pagar os custos urgentes do evento.

**Comment by Lorenaps** [comment]
Incluir bolsas de inscrição para a apoiadora com o local

**Comment by felipythondev** [comment]
@Lorenaps e @cecivieira essa issue aqui está pronta? 👀
Me parece que sim.
