### ISSUE TITLE
Pesquisar e listar as plataformas de inscrição para evento - Sympla, Eventbrite

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#55]

**Comment by cecivieira** [comment]
Tem uma pesquisa sobre plataforma de inscrição nessa issue:
https://github.com/pythonbrasil/pybr2022-org/issues/92

Talvez valha a pena Arthur ler essa issue e a partir daí decidir se vale a pena refazer esse estudo ou só usar a roda que já existe

**Comment by arthurcarneiro** [comment]
Olá, vou ler a pesquisa e dar uma olhada nos sites. Além do eventbrite e sympla, vou ver outras que estão em ascensão no momento nesse segmento. Em breve trago o que achar.

**Comment by cecivieira** [comment]
@arthurcarneiro existe um formulário padrão para coleta de dados de inscrições. Se for escolher outra, só precisa lembrar de pegar esse formulário e implementar na nova plataforma.

**Comment by arthurcarneiro** [comment]
Pesquisei as plataformas citadas acima e ainda a inti. Atualmente a sympla é a que dispõe do melhor serviço com relação a gerenciamento do evento. Desde a plataforma de pagamento à comunicação com os participantes.
