### ISSUE TITLE
[Reunião] Geral: 27 fev. 2023

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#57]
# Reunião Geral - 27/02/2023

- Data: 27 fev. 2023 
- Participantes:
  - Nome e Sobrenome (@Github ou E-mail)
  - Lorena Pereira (@Lorenaps)
  - Ryllari Marques (@Ryllari)
  - Débora Oliveira (@deboraos)
  - Arthur Carneiro (@arthurcarneiro)
  - Mariana Bedran (@maribedran)
  - Leonardo Leano (@LeonardoLeano333)
  - Juliana Barros Lima (@tiidadavena)
  - Patricia Silva (@patriciasilvarecife)

## Ata

_Adicione os itens que foram discutidos durante a reunião._

- #27 #26 Pedir orçamento de Almoço e de lanche com opção vegana 
https://docs.google.com/spreadsheets/d/1IkS1q6fxycsn6wznbBuKaSsL9EXoIAI0BvOGbdMEf-8/edit#gid=0
Lorena apresentou os orçcamentos das refeições e as projeções dos valores dentro da planilha de custos. O valor diário estimado para o lanche foi de R$ 16/dia e para lanche R$ 16 e para almoço ficou R$ 25 / dia. A  depender do local do evento e das proximidades deste com outros locais de alimentação, talvez não seja necessária a contratação para buffet de almoço para não encarecer demais o valor do ingresso.
A empresa fornecedora informou que vai precisar de jarras de vidro mas que conta com serviço de montagem, arrumação de mesa.
- #61 Atualização dos Grupos de Trabalho 
https://github.com/pythonNordeste/organizacao-pyne-2023/issues/61
Ryllari se prontificou para entrar no time de Patrocínio. 
Mari Bedran propôs uma reunião mais curta para alinhamento do time de Conteúdo.
Foi concordado que a Comissão Representativa pode contar com pessoas de outras cidades fora de Salvador, e que as pessoas líderes dos GTs serão convidades a integrar a Comissão.
- Reports dos GTs
    - Comunicação:
        - Todos os templates foram solicitados para Carol, estão em construção e devem ser entregues até o dia 01/03/2023
        - O link do Plano de Patrocínio está disponível para edição dos times de comunicação e de patrocínio para edição
        - Sem atualizações no site
- #42 Pensar na estrutura de conteúdo
https://docs.google.com/spreadsheets/d/1Crs_T_iqoLWPmWzt4CkNVGjZczZzyniTGc7vj9tzIU8/edit#gid=401476289
Será melhor discutido durante a reunião do GT de Conteúdo.

### Ações para serem realizadas

- [ ] Definição da Comissão Representativa (confirmar com as pessoas envolvidas)
    - Débora Oliveira (@deboraos)
    - Mariana Bedran (@maribedran)
    - Patricia Silva (@patriciasilvarecife)
    - Ana Cecília Vieira (@cecivieira)
    - 5a pessoa: @Lorenaps vai entrar em contato com pessoas de Salvador para fechar a representação local do evento junto com @deboraos
    
    A função da comissão é fiscalizar o andamento dos grupos de trabalho e garantir que as tarefas estão em dia e sem impedimentos. A comissão tem o papel de gestão, não de execução, então cabe a cada líder de grupo verificar que tem pessoas para realizar as ações e reportar ao grupo geral se houver impedimentos ou falta de pessoal.
    A Comissão tem abertura para tirar quaisquer dúvidas com outras lideranças da comunidade. 
    
- #62 Criação de um rascunho de calendário geral do evento para planejamento de prazos (@Ryllari)
- #42 Marcar reunião para rever estrutura de conteúdo (@maribedran) - 28/02 às 
- #54 Agendar reunião do GT de Operacional com o Financeiro para a semana que vem (@pythonNordeste/operacional-2023)
- [#58, #52, #51, #50, #49, #46](https://github.com/pythonNordeste/organizacao-pyne-2023/issues?q=is%3Aissue+is%3Aopen+template+label%3Acomunica%C3%A7%C3%A3o) Apresentar os resultados das artes (@pythonNordeste/comunicacao-2023)

**Comment by cecivieira** [comment]
#27 #26

**Comment by Lorenaps** [comment]
Atualizar e unificar as informações sobre os grupos de trabalho #61.

**Comment by kim-soares** [comment]
Pessoal, tenho disposição para participar da Comissão Representativa. Eu mudei de Salvador nessas últimas semanas e por isso não tinha comentado antes, mas agora vi que não estar na cidade não é um impeditivo, se acharem proveitoso, posso participar!
