### ISSUE TITLE
Template para feed

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#58]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Template para publicação de informações nos feeds das redes sociais.  

### Detalhamento do uso
A peça seria apenas um template sem nenhuma informação, apenas a identidade visual e bastante espaço para que a organização possa escrever avisos.

### Data prevista para uso da arte
28 fev 2023

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
@ElisLages nessa arte de patrocínio existe uma página que não tá com a tag de cota. Ele seria o template para feed?

![image](https://user-images.githubusercontent.com/30605862/229826115-e604d3eb-7e9d-4c47-9208-04d1565834c6.png)

**Comment by ElisLages** [comment]
Não, @cecivieira. Acho que quando foi replicado ficou a mais. Pode ignorar.

**Comment by kim-soares** [comment]
Pessoal, deixando aqui **minha sugestão** de layout para a peça nas redes sociais de **"chamada para pessoas voluntárias"** .

Meu racional foi: Remover o texto para deixar o layout mais limpo. O texto vai para legenda, não havendo necessidade de ir na peça.



![Sugestão de layout (1)](https://user-images.githubusercontent.com/126588830/234960686-735ecc72-e52c-40d6-be8b-6ffbd7533b8d.png)

**Comment by ElisLages** [comment]
Oi, @kim-soares, eu estava pensando como você, com o texto no corpo da legenda. Se quiser deixar esse modelo no canva, fica a vontade, tá?

**Comment by kim-soares** [comment]
@ElisLages o modelo já tá lá :)
