### ISSUE TITLE
Arte para Plano de patrocínio

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#59]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Aplicar identidade visual no plano de patrocínio #14 

Criar arte nesse slide: https://docs.google.com/presentation/d/11gaBGzRilHVKkTFi4NzUg7s4bylh42FHx7-AElNQaIQ/edit?usp=sharing

### Detalhamento do uso
Uso no plano de patrocínio que será enviado para empresas potenciais patrocinadoras.

### Data prevista para uso da arte
06 março

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *[slide](https://docs.google.com/presentation/d/11gaBGzRilHVKkTFi4NzUg7s4bylh42FHx7-AElNQaIQ/edit?usp=sharing)*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
Inspirações:
Fortaleza - https://docs.google.com/presentation/d/1ZhP8osCF55aN9_v9eVVcWNf71PNTboDctqPxknuUdgo/edit?
Aracahú - https://www.canva.com/design/DAFYbRqxCAc/RzXEhovJ1WrOEzg0u3VlcQ/edit?utm_content=DAFYbRqxCAc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by cecivieira** [comment]
Descrição sobre a cidade:
https://docs.google.com/document/d/1yL8UTwD-sqZtvLZEOx_tbmCy30rUKu9YG4KjE6sxCf4/edit

**Comment by ElisLages** [comment]
Olá, começamos a ideação da arte, podem visualizar aqui - https://docs.google.com/presentation/d/1QzBcQxBwyZ31W7SatohcUQtLRVZpXcdPjW3TF0dzZ6Y/edit#slide=id.gc6f59039d_0_20

**Comment by ElisLages** [comment]
Gente, a maior parte da edição do PP está no Canva. 
Os textos que estão inclusos, são parte do PP de Aracaju, parte do que estavam escrevendo no docs. Estes, podem (e devem) ser revisados, pelo grupo responsável por essa escrita. 

Podem acessar aqui: https://www.canva.com/design/DAFb99OaRTU/8l6dlc1to_EuKG6I4X-Szw/edit?utm_content=DAFb99OaRTU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by cecivieira** [comment]
@ElisLages fiquei confusa. É para considerar o plano de patrocínio do canva ou Google drive?
Pretendo fechar uma proposta esse final de semana.

**Comment by ElisLages** [comment]
Perdão, @cecivieira, realmente ficou confuso. 
É pra considerar a arte do Canva.

**Comment by cecivieira** [comment]
@ElisLages dei uma olhada no plano e vi que Ju também revisou.
Além dos comentários que ela fez, acho que só precisa atualizar a fote do título dos slides vermelhos, para padronizar com os demais.

Também acho que o vermelho pode ser alterado para uma cor mais suave

**Comment by cecivieira** [comment]
Arte entregue
