### ISSUE TITLE
Adicionar no formulário de inscrição perguntas sobre restrições alimentares

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#60]
### Descrição
Adicionar no formulátio de inscrição perguntas sobre restrições alimentares, seja ele no google docs ou em outra ferramenta de gerenciamento de inscrição. Mas precisamos coletar as restrições dos participantes previamente para passarmos para a equipe de coffee break.

Diminuir ao máximo a necessidade da participante usar o campo aberto para responder as perguntas, vistos as dificuldades na análise. Um opção para isso pode ser adicionar uma lista com 10 (ou outra quantidade razoável) de restrições mais comuns. 

### Requisitos para a atividade ser considerada como concluída
- [ ] Testar as perguntas com os membros da equipe primeiro;
- [ ] Fazer as correções necessários a partir dos testes;
- [ ] Visualizar as perguntas corrigidas no formulário de inscrição

**Comment by cecivieira** [comment]
@Lorenaps tendo em vista que não forneceremos almoço, esse campo é necessário?
Acho que poderíamos pegar um coffee com opções veganas ou, no mínimo, vegetarianas.
