### ISSUE TITLE
Criar cronograma da organização do evento

### ISSUE THREAD

**Issue by Ryllari** [pythonNordeste/organizacao-pyne-2023#62]
### Descrição
*Definir um calendário de ações a serem realizadas pela organização do evento com um cronograma do que ser feito e o prazo máximo a ser realizado.*
*Ex:
- Divulgar data da Python Nordeste (oficializar): DD/MM/YYYY
- Divulgar keynotes
- Vendas 1° Lote DD/MM/YYYY - DD/MM/YYYY
- Vendas 2° Lote DD/MM/YYYY - DD/MM/YYYY
- Abrir submissão de palestras DD/MM/YYYY
- Abrir submissão de tutoriais DD/MM/YYYY
*

### Requisitos para a atividade ser considerada como concluída
- Ter todas as datas de ações principais da organização do evento (públicas e privadas) mapeadas
- Ter a data do evento definida para tê-la como base para a montagem do calendário
- Ter o calendário finalizado e apresentado a organização

**Comment by kim-soares** [comment]
@Ryllari Complementando aqui:

- Divulgar data da Python Nordeste (oficializar): DD/MM/YYYY
- Divulgar keynotes
- Vendas 1° Lote DD/MM/YYYY - DD/MM/YYYY
- Vendas 2° Lote DD/MM/YYYY - DD/MM/YYYY
- Abrir submissão de palestras - DD/MM/YYYY
- Abrir submissão de tutoriais - DD/MM/YYYY
- Divulgar palestras aprovadas - DD/MM/YYYY
- Divulgar tutoriais aprovados - DD/MM/YYYY

**Comment by kim-soares** [comment]
@Ryllari essa divulgação vai ser através de quais canais? Pensei em LinkedIn, Instagram, Twitter, email. É isso?

**Comment by jadefigueredo** [comment]
Atualizando com mudanças já feitas @kim-soares @Ryllari - Qualquer coisa, olhar Issue #70 

### Descrição

*Definir um calendário de ações a serem realizadas pela organização do evento com um cronograma do que ser feito e o prazo máximo a ser realizado.*

*Ex:
- [x] Divulgar data da Python Nordeste: *22, 23 e 24 de Setembro de 2023*
- [ ] Divulgar keynotes
- [x] Vendas 1° Lote DD/MM/YYYY - DD/MM/YYYY
- [ ] Vendas 2° Lote DD/MM/YYYY - DD/MM/YYYY
- [x] Abrir submissão de palestras - 20/05/2023
- [x] Abrir submissão de tutoriais - DD/MM/YYYY
- [ ] Divulgar palestras aprovadas - DD/MM/YYYY
- [ ] Divulgar submissão de tutoriais DD/MM/YYYY
- [ ] Divulgar tutoriais aprovados - DD/MM/YYYY


### Requisitos para a atividade ser considerada como concluída:

- [ ] Ter todas as datas de ações principais da organização do evento (públicas e privadas) mapeadas
- [x] Ter a data do evento definida para tê-la como base para a montagem do calendário
- [ ] Ter o calendário finalizado e apresentado a organização

**Comment by felipythondev** [comment]
https://github.com/pythonNordeste/organizacao-pyne-2023/issues/70#issuecomment-1535580079

feito!
