### ISSUE TITLE
## Comissão Representativa do Evento

### ISSUE THREAD

**Issue by AndressaLF** [pythonNordeste/organizacao-pyne-2023#64]
## Comissão Representativa do Evento
> Pelo menos 2 pessoas que assumam a representção do evento. 
> **Assumir a representação significa** ajudar na orientação dos grupos de trabalho, na definição de prioridades e também ser a equipe porta-voz do evento, se apresentando a comunidade como tal. 
> **Assumir a representação NÃO significa** fazer todas as atividades necessárias para a realização do evento sozinha, as atividades e decisões devem ser partilhadas com todos os respectivos grupos de trabalho.

**? - Definição urgente!**

#### Responsável pela construção da identidade visual do evento e dos textos que o descrevem. Responsável também pelo planejamento das interações com o público alvo e execução dessas interações nas redes socias e site.
> Atividades como: Criar identidade visual, Criar peças de design, Gerenciar redes sociais, Construir o site

- Elis Lages (@ElisLages) - **Líder do grupo \o/**
- Juliana Barros Lima (@tiidadavena)
- Patricia Silva (@PatriciaSilvaRecife)
- Ana Cecília Vieira (@cecivieira)
- Carine Neris (@Carine-Neris)
- Lorena Pereira (@Lorenaps )
- Daniel (@)
- Carol Barreto (@)

#### Responsável pela construção da carta de patrocínio e pela execução dos fluxos de patrocínio, desde a captação até o recebimento de recursos e prestação de contas das contrapartidas negociadas.
> Atividades como: Criar material para patrocinadores, Contatar empresas

- Geisa Santos (@geisasantos)
- Felipe de Morais (@lipemorais)
- Ana Cecília Vieira (@cecivieira)
- Ryllari Marques(@Ryllari )

#### Responsável pelo gerenciamento da aquisição de produtos e serviços necessários à realização do evento - do orçamento até aquisição e execução do serviço no evento. Responsável também pelo gerenciamento das inscrições e credenciamento. Possui contato direto com a equipe Financeira devido a construção da planilha de previsão orçamentária e necessidade de pagamento dos fornecedores.
> Atividades como: Contatar com fornecedor, Adquirir de serviços, Organizar monitores, Gerenciar inscrição e credenciamento

- Fernando Telles (@) - **Líder do grupo \o/**
- Fábio Bispo (@fabiobj )
- Débora Santana (@deboraos)
- Lorena Pereira (@Lorenaps )

#### Responsável pela execução do fluxo de entrada e saída de dinheiro do evento.
>  Atividades como: Controlar entrada e saída de dinheiro, venda de ingresso, programa de Auxílio Financeiro

- Ana Cecília Vieira (@cecivieira) - **Líder do grupo \o/**
- Mariana Bedran Lesche (@maribedran)

#### Responsável pela construção e execução da grade de conteúdo do evento.
> Atividades como: Criar o formulário de submissão, Estabelecer critérios para seleção de atividade, Estabelecer metodologia para revisão das propostas, Montagem da programação

- Mariana Bedran Lesche (@maribedran) - **Líder do grupo \o/**
- Humberto Diógenes (@hdiogenes )
- Rafael Gomes (@gomex)
- Ana Cecília Vieira (@cecivieira)
- Lorena Pereira (@Lorenaps)
- Leonardo Leano (@LeonardoLeano333)

#### Responsável por receber e responder aos contatos referentes ao código de conduta - CDC, tanto com relação aos participantes quanto com relação a organização.
> Obs: Importante que não seja ninguém da organização

- Ana Cecília Vieira (@cecivieira) ficou de recrutar o grupo do CDC.
- Andressa Lima (@andressalferreira)

_Originally posted by @Lorenaps in https://github.com/pythonNordeste/organizacao-pyne-2023/issues/61#issuecomment-1440727577_

**Comment by cecivieira** [comment]
@AndressaLF n~ao entendi essa issue. 
Qual 'e a atividade que deve ser realizada?

**Comment by AndressaLF** [comment]
@cecivieira abri essa issue sem querer, quando tentava adicionar meu nome no grupo do CDC. Desculpa!
