### ISSUE TITLE
Falar com UFBA para local do evento

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#7]
Ver se UFBA tem um lugar que atenda os requisitos da ata: https://github.com/pythonNordeste/organizacao-pyne-2023/blob/main/atas/2022-12-12.md

**Comment by lipemorais** [comment]
@Lorenaps teve retorno da UFBA e esta aguardando para marcar uma ligação com a professora para ver os próximos passos.

**Comment by cecivieira** [comment]
@Lorenaps o contato foi respondido com interesse pelo diretor da escola politécnica da ufba. Enviei a estrutura necessária

**Comment by cecivieira** [comment]
Resumo reunião com a UFBA 13 fev. 2023


LabGrad - 3 laboratórios com 15 computadores
Auditório principal - capacidade de 200 lugares
22 a 24 de setembro

R$5mil dia por auditório.
Possibilidade da universidade entrar como Apoio .

Espaços solicitados:
1 Auditório principal com a capacidade para alocar completamente o público estimado (entre 200 e 300 pessoas)
1 Auditório auxiliar, que comporte no mínimo 50 pessoas e que seja próximo do auditório principal, de preferência.
1 espaço aberto ou fechado onde seja possível colocarmos alguns stands
Entre 2 e 4 laboratórios de informática
1 sala de apoio para a equipe de organização (pode ser uma sala de aula mesmo)
1 sala para espaço kids
1 sala para open space
Área para coffee break
Local que que facilite a acessibilidade
Estrutura de wifi

enviar e-mail com:
- Valores previstos de ingressos (na edição anterior o primeiro lote custou R$97,19
- Lista de espaços necessários
- Estimativa de custos do evento

**Comment by Lorenaps** [comment]
Email com listas dos espaços solicitados:
(enviado com cópia pro nordeste@python.org.br)


-     1 Auditório principal com a capacidade para alocar completamente o público estimado (entre 200 e 300 pessoas)
-     1 Auditório auxiliar, que comporte no mínimo 50 pessoas e que seja próximo do auditório principal, de preferência
-     1 Espaço para Open Space (Espaço para que as pessoas possam se reunir e falar sobre seus projetos)
-     1 Espaço aberto ou fechado onde seja possível colocarmos alguns stands de empresas patrocinadoras
-     Entre 2 e 4 laboratórios de informática
-     1 Sala de apoio para a equipe de organização (pode ser uma sala de aula mesmo)
-     1 Sala para Espaço Kids (pode ser uma sala de aula mesmo)
-     Área para coffee break
-     Além desses espaços é importante que o local tenha acessibilidade predial (para possibilitar a locomoção de pessoas com diferentes necessidades) e WIFI.

**Comment by cecivieira** [comment]
Resposta UFBA:

Prezada Lorena

Confirmo o recebimento. Conforme conversamos, dos itens listados temos:

01 auditório para 200 pessoas - 6º andar
01 auditório para 80 pessoas - 6º andar
01 auditório para 35 pessoas  - 6º andar - Sala de apoio para a equipe de organização
Espaço para stands e coffee break: foyer dos auditórios  - 6º andar
Espaço para Open Space, 1 Sala para Espaço Kids - 02 salas de aula do sétimo andar (espaço kids na sala 7.3.7 e Open space na 7.3.6)
Acessibilidade: auditórios tem rampa de acesso e 7º andar tem acesso por elevador
Laboratórios de informática: Pré-reserva de 02, podendo ampliar para 03 a depender das demandas de atividades da Escola no semestre 2023.2

Questões-chave:
Sábado e domingo - Professora Karla e Grupo de pesquisa ficam responsáveis pela abertura, fechamento e desligamento dos equipamentos dos auditórios. Horário limite: 17 horas. 
Valores da cessão dos auditórios - comprovação da finalidade não lucrativa do evento por meio de fornecimento de valores das inscrições e estrutura de custos / possibilidade de isenção via inserção da Escola como apoiadora e/ou fornecimento de algumas inscrições gratuitas para estudantes da escola

**Deverei conversar com a Direção entre os dias 27/02 e 03/03 para ver os possíveis encaminhamentos.**

**Comment by Lorenaps** [comment]
Email respondido conforme [link](https://docs.google.com/document/d/1PboNoEUUqtOUJqRBdlz1VclIkbkzC1iD4z3QUAEAa10/edit).

**Comment by Lorenaps** [comment]
Aguardando retorno. Prazo inicial de resposta 03/03, um novo email perguntando se havia alguma dúvida com as informações anteriores foi enviado nesse mesmo dia, ainda sem resposta.

**Comment by Lorenaps** [comment]
UFBA ainda está aguardando reunião com a diretoria para retornar se conseguiremos ou não fazer o evento lá. Novo prazo é até o final dessa semana.

**Comment by Lorenaps** [comment]
Ainda não tivemos retorno na ultima semana e seguimos aguardando.
