### ISSUE TITLE
Definir calendário de submissão de trabalhos 

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#70]
### Descrição

- Abertura da chamada de trabalhos
- Fechamento das submissões 
- Prazo de revisão dos avaliadores 
- Decisão final dos aprovados
- Resposta de aceite
- Prazo para confirmação de presença 
- Contato com lista de espera caso haja desistências 
- Definição da grade
- Publicação da grade

### Requisitos para a atividade ser considerada como concluída

Criar eventos no calendário da org para cada item

**Comment by maribedran** [comment]
- Abertura da chamada de trabalhos - 24/04
- Fechamento das submissões - 02/07
- Prazo de revisão dos avaliadores - 15/07
- Decisão final dos aprovados - 17/07
- Resposta de aceite - 21/07
- Prazo para confirmação de presença - 28/07
- Contato com lista de espera caso haja desistências - 29/07
- Definição da grade - 01/08
- Publicação da grade - 04/08

**Comment by cecivieira** [comment]
| Data | Descrição |
| ----------- | ---------------- |
| 20 maio | Abertura da chamada de trabalhos |
| 18 jun. | Fechamento das submissões |
| 07 jul. | Prazo de revisão dos avaliadores |
| 10 jul. | Decisão final das aprovadas |
| 13 jul. | Envio de resposta para aprovadas |
| 21 jul. | Resposta das aprovadas aceitando apresentar-se no evento|
| 22 jul. | Contato com lista de espera caso haja desistências|
| 26 jul. | Definição da grade|
| 01 ago. | Publicação da grade|

**Comment by ElisLages** [comment]
Oi gente, a arte de CFP já tá no canva, queria saber se já tem formulário pronto.

**Comment by maribedran** [comment]
A gente tá esperando a plataforma responder se vamos ter desconto

**Comment by ElisLages** [comment]
Massa, Mari. Valeu a resposta.
