### ISSUE TITLE
Definir equipe de mentoria para submissão de atividades 

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#71]
### Descrição
Chamar pessoas voluntárias para se disponibilizar a orientar na criação de propostas de atividade e elaboração do conteúdo.

Os contatos das pessoas voluntárias ficarão disponíveis na chamada de trabalhos com um texto incentivando aquelas que necessitem de ajuda para formular suas propostas de atividade ou para revisá-las, assim como para elaboração e revisão das atividades já aceitas. 

### Requisitos para a atividade ser considerada como concluída

O grupo deve ser composto por pessoas diferentes das que vão avaliar as propostas e incluir pessoas de grupos sociais subrepresentados na comunidade.

**Comment by felipythondev** [comment]
Falou com algumas pessoas próximas mas precisa retomar. É necessário re-divulgar a chamada de palestras para chamar atenção. @pythonNordeste/conteudo-2023, podem ajudar nesse ponto aqui, pls 🫶🏾
