### ISSUE TITLE
Definir equipe de avaliação de propostas de trabalho 

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#72]
### Descrição

Chamar pessoas voluntárias para avaliar as submissões de atividades.

- A equipe deve incluir pessoas de grupos subrepresnetados na comunidade que não façam parte da equipe de mentoria de conteúdo. 
- As pessoas devem garantir que estarão disponíveis para ler as propostas dentro do prazo definido no calendário de atividades das submissões.

**Comment by cecivieira** [comment]
@maribedran tivemos muitas propostas?
Tu acha que precisará ter mais gente do que nós para avaliar as submissões?

**Comment by maribedran** [comment]
Tivemos 123 propostas. Quanto mais gente melhor. Já tinha falado com algumas pessoas que se dispuseram a ajudar, mas idealmente teria mais gente.

**Comment by cecivieira** [comment]
Tu acha necessário fazer uma chamada nas redes sociais para encontrar
avaliadoras?

**Comment by maribedran** [comment]
Não sei se é necessário, mas acho interessante pra trazer diversidade pras avaliações.

**Comment by felipythondev** [comment]
Ainda tem muitas propostas somente com uma avaliação. @maribedran ficou de fazer as avaliações. Assim que terminar vamos marcar uma reunião para fechar a programação do evento.
