### ISSUE TITLE
Criar texto da chamada de atividades

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#73]
### Descrição
Usar chamada da edição anterior e editar caso seja necessário.

**Comment by maribedran** [comment]
Procurei as chamadas de atividade de anos anteriores no drive e achei o de 2019. Fiz uma cópia e marquei em amarelo as informações que têm que ser atualizadas.

Alguma observação mais geral sobre o processo?

**Comment by PatriciaSilvaRecife** [comment]
Por mim usa esta chamada mesmo, Mari. As mudanças necessárias são essas que apontasse.
