### ISSUE TITLE
Cadastrar chamada de atividades na plataforma

### ISSUE THREAD

**Issue by maribedran** [pythonNordeste/organizacao-pyne-2023#74]
### Descrição

A princípio a plataforma utilizada será a Pretalxs

**Comment by cecivieira** [comment]
@maribedran a plataforma dá desconto de 25% para comunidades, mas precisa fazer isso mandando e-mail pra lá.
Tu ppderia fazer essa solicitação?

**Comment by cecivieira** [comment]
Inserido o formulário de submissão de atividades. Precisa testar
@renan-assis-santos como testa a submissão de atividades no pretalx?
