### ISSUE TITLE
[Reunião] Geral: 03 abr. 23

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#77]
# Reunião Geral

- Data: 03 abr. 23
- Participantes:
  - Felipe de Morais (@lipemorais)
  - Mari Bedran (@maribedran)
  - Lea Sampaio (@leasampaio)
  - Arthur Carneiro (@arthurcarneiro)
  - Patrícia Silva (@patriciasilvarecife)
  - Ana Cecília Vieira (@cecivieira)

## Ata

- #10 forneceremos comida?
- Atualização das redes sociais ( #47 banner; avatar; nome "2023"; etc)
    - Twitter: https://twitter.com/PythonNordeste
    - LinkedIn: https://www.linkedin.com/company/python-nordeste-2022/
        ! Existem duas páginas no LinkedIn da Python. Seria bom excluir a conta com menos seguidores (https://www.linkedin.com/company/pythonnordeste2022/about/)
    - Facebook: https://www.facebook.com/PythonNordeste/?locale=pt_BR
    - Youtube: https://www.youtube.com/@PythonNordeste
- 

### Ações para serem realizadas

- [ ] Reunião para fechar estrutura de conteúdo #42 (@maribedran)

**Comment by cecivieira** [comment]
#10 forneceremos comida?

**Comment by kim-soares** [comment]
Atualização das redes sociais (banner; avatar; nome "2023"; etc)
- Twitter: https://twitter.com/PythonNordeste
- LinkedIn: https://www.linkedin.com/company/python-nordeste-2022/
! Existem duas páginas no LinkedIn da Python. Seria bom excluir a conta com menos seguidores (https://www.linkedin.com/company/pythonnordeste2022/about/)
- Facebook: https://www.facebook.com/PythonNordeste/?locale=pt_BR

**Comment by kim-soares** [comment]
@maribedran eu vi foram atualizados os avatares das redes sociais, mas o banner continua antigo. Precisa de uma nova arte para substituir.

**Comment by maribedran** [comment]
@kim-soares acho que @ElisLages tá cuidando dessa área.

**Comment by ElisLages** [comment]
Cecilia comentou que solicitou as credenciais de acesso do linkedin e facebook.
