### ISSUE TITLE
falar com as pessoas da Faculdade Visconde de Cairu para local do evento

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#8]
Precisa atender os requisitos da ata: https://github.com/pythonNordeste/organizacao-pyne-2023/blob/main/atas/2022-12-12.md

**Comment by lipemorais** [comment]
Sem novidades até agora.

**Comment by cecivieira** [comment]
Decidido o local pela UFBA #7
