### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by kim-soares** [pythonNordeste/organizacao-pyne-2023#81]
Contato:

[Guilherme M Santos](https://www.linkedin.com/in/iamguisantos/)
IamGuiSantos@GitHub.com

**Comment by cecivieira** [comment]
- GitHub: não vai conseguir patrocinar esse ano.

**Comment by kim-soares** [comment]
@cecivieira a "fonte" é a nossa troca de emails, beleza?! Eu só fiz divulgar pro time.

**Comment by cecivieira** [comment]
Massa
Retirei a fonte do comentário
