### ISSUE TITLE
Divulgação do plano de patrocínio

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2023#86]
### Peça/publicidade solicitada
Cartões para redes sociais

### Detalhamento do uso
Divulgação do plano de patrocínio. 
Convidar empresas para patrocinar o evento

### Data prevista para uso da arte
17 abr.

### Quais informações devem aparecer na arte
Frase simples informando sobre a publicação do plano de patrocínio

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by Lorenaps** [comment]
Identidade visual da escola politecnica: http://www.eng.ufba.br/identidade-visual

**Comment by cecivieira** [comment]
https://www.instagram.com/p/Cr_6m6arx9n/
