### ISSUE TITLE
Submeter formulário de ajuda de custos para a PSF

### ISSUE THREAD

**Issue by lipemorais** [pythonNordeste/organizacao-pyne-2023#88]
Solicitar patrocínio para a PSF através do formulário: https://psfmember.org/grant-proposals/

**Comment by felipythondev** [comment]
Comecei a preencher o formulário mas vou precisar de algumas informações. Como:

- [x] Página de orientações sobre COVID-19 da conferência
- [x] Grade da conferência(Link to Conference Schedule) => https://pretalx.com/python-nordeste-2023/schedule/
- [x] O que podemos oferecer nessa pergunta? =>
```
Follow-up activities *
Provide a description of the planned grant follow-up activities. If this grant is approved, we will send you a link to our report form. In addition to that, we want to know how post event/project information will be shared with the community. This could be blog postings, post-event write-ups, web pages, project updates, where recordings will be posted, etc.
```

**Comment by lipemorais** [comment]
Utilizar o mesmo que temos na proposta de patrocínio. Publicação nas redes sociais e tudo mais que tem lá.

**Comment by lipemorais** [comment]
@pythonNordeste/conteudo-2023, pessoal! Preciso de ajuda com os primeiros 2 pontos ali de orientações sobre covid e grade do evento. Podemos ver como colocar esses pontos no site para que eu possa fazer a solicitação de patrocínio a PSF?

**Comment by cecivieira** [comment]
@lipemorais a grade do evento vai demorar bastante para ser publicada. Você precisa apenas do espaço reservado no site sobre isso?

**Comment by felipythondev** [comment]
@cecivieira podemos tentar só com os espaços reservados.

**Comment by cecivieira** [comment]
@leasampaio @jadefigueredo precisaremos criar uma página com indicações sobre covid no site.
Fiz a tradução automática da PyCon2023. Vocês poderiam ajustar o texto e deixar APENAS coisas relacionadas a pandemia?

https://docs.google.com/document/d/1V0SPL7pxRAFJYpYaJEVf7Bz4TTRQJmEcbA1LCfF81Ag/edit#heading=h.bpzjk2vvg272

**Comment by felipythondev** [comment]
@maribedran vai terminar de preencher o pretalx para a gente poder ter o link da grade do evento direto pra lá. Vai fazer hoje.

**Comment by maribedran** [comment]
@lipemorais https://pretalx.com/python-nordeste-2023/schedule/

**Comment by tiidadavena** [comment]
> @lipemorais https://pretalx.com/python-nordeste-2023/schedule/

O time do site vai adicionar o link do Pretalx no site para fins de celeridade na solicitação para a PSF, mas vamos procurar ver uma forma de apresentar a grade sem precisar da pessoa usuária ser redirecionada para outro site.

**Comment by felipythondev** [comment]
Pessoal, notei que no formulário solicita que a venda de ingressos esteja aberta. Quando vão ser aberta a venda de ingressos?

**Comment by felipythondev** [comment]
@cecivieira sabe quando devem abrir a venda de ingressos?

**Comment by cecivieira** [comment]
https://www.eventbrite.com.br/e/python-nordeste-2023-tickets-685066200447

Link para a venda de ingressos.
A previsão que hoje vá para o ar

**Comment by felipythondev** [comment]
Submeti o formulário da PSF. Pedi 4k de dólares.

**Comment by cecivieira** [comment]
Conta para receber dinheiro:

Razão Social | Associação Python Brasil
CNPJ | 09.344.485/0001-05
Banco | 001 Banco do Brasil
Agência | 0089-2
Conta Corrente | 78126-6
IBAN | BR0600000000000890000781266C1
BIC | BRASBRRJBNU

**Comment by tiidadavena** [comment]
Logo da PSF adicionada no site: https://pyne2023.onrender.com/
