### ISSUE TITLE
falar com as pessoas do Mundo Plaza para local do evento 

### ISSUE THREAD

**Issue by gomex** [pythonNordeste/organizacao-pyne-2023#9]
Ver com Tupy, pois existe possibilidade de usar as parcerias

Precisa atender os requisitos da ata: https://github.com/pythonNordeste/organizacao-pyne-2023/blob/main/atas/2022-12-12.md

**Comment by lipemorais** [comment]
Sem novidades até agora.

**Comment by cecivieira** [comment]
Decidido o local pela UFBA #7
