### ISSUE TITLE
Tratativa de patrocinio <> Botcity

### ISSUE THREAD

**Issue by kim-soares** [pythonNordeste/organizacao-pyne-2023#90]
Dar continuidade através de email.

- [x] Coleta de dados da empresa
- [x] Envio do contrato
- [x] Emissão de NF
- [x] Confirmação do pagamento

**Comment by kim-soares** [comment]
@cecivieira e @lipemorais 

Pessoal, contrato pronto. Vocês podem revisar para mim?

https://docs.google.com/document/d/1mnPCZGlNgruyiy4XcUXZLKjqtwr2OJ5Age8LELzIREw/edit

**Comment by lipemorais** [comment]
Oi, @kim-soares esse contrato está tudo certo pelo que vi aqui.

**Comment by lipemorais** [comment]
@kim-soares vai usar ou o DocuSign ou o Autentique.com.br para enviar para assinar o contrato.

**Comment by cecivieira** [comment]
Pagamento agendado para 01 junho

**Comment by cecivieira** [comment]
Pagamento recebido

**Comment by cecivieira** [comment]
@lipemorais respondendo aqui as dúvidas da patrocinadora

>- quais as dimensões do stand?
>- quais mobiliários estarão disponíveis para uso?
>- existe fornecedor preferencial para aluguel de mobília?
Fiz esses questionamentos para a UFBA

>- quais os tamanhos de logomarca que precisamos enviar?
>- para quem/onde eu mando as versões da logomarca?
>- há definição de tipo ou tamanho de texto para estas postagens?
Solicitar preenchimento do formulário abaixo:
https://docs.google.com/forms/d/e/1FAIpQLSdM-bWCHH04a0S4AQg7TdmLVOBzQWJViVIvfqJ6P_RIqPEZ5Q/viewform?usp=sharing

>- quando será a postagem exclusiva e qual o prazo para envio de texto para ele e para o email marketing?
Assim que recebermos as informações coletadas pelo formulário agendaremos a postagem.

>- qual será o tamanho dos banners?
Os banners aonde figurarão a logomarca da empresa serão confeccionados pela organização do evento. Ainda estamos em fase de desenvolvimento das peças.

**Comment by felipythondev** [comment]
- Tive a conversa com o pessoa da BotCity. Vou aguardar o retorno da UFBA para responder as perguntas sobre stand.
- Enviei por e-mail o formulário de patrocinador.
- Sobre a postagem exclusiva disse que eles podem enviar no momento que acharem mais pertinente, antes ou depois do evento.
- O tamanho ainda não foram definidos, estamos pensando em algumas possibilidades de tamanho.
