### ISSUE TITLE
Tratativa de patrocinio <> Globo

### ISSUE THREAD

**Issue by kim-soares** [pythonNordeste/organizacao-pyne-2023#91]
Dar continuidade através de email.

- [x] Coleta de dados da empresa
- [x] Envio do contrato
- [x] Emissão de NF
- [x] Confirmação do pagamento

**Comment by lipemorais** [comment]
Aguardando o @muriloviana  emitir a nota fiscal para gente seguir aqui.

**Comment by lipemorais** [comment]
Enviei a nota fiscal da Globo e perguntei sobre quando pretendem fazer o pagamento.

**Comment by felipythondev** [comment]
O pagamento está agendando para 05/Jun/2023

**Comment by cecivieira** [comment]
Pagamento recebido

**Comment by cecivieira** [comment]
@lipemorais o cupom de desconto para a patrocinadora está aqui:
https://docs.google.com/spreadsheets/d/1I5WQ4SDQHBZqKh0hEhvKIdvOEhCF7ZOJ7JvaDKAwVu8/edit#gid=0

O desconto só é aplicado na categoria de ingresso "convidadas"

**Comment by felipythondev** [comment]
Enviado a empresa patrocinadora.
