### ISSUE TITLE
Revisar minuta de contrato de patrocínio

### ISSUE THREAD

**Issue by kim-soares** [pythonNordeste/organizacao-pyne-2023#92]
Pessoal, temos um modelo de minuta de contrato de patrocínio de 2022, estou abrindo a issue para ser feita a revisão e validão desse documento. A partir disso começaremos a enviar para as empresas parcerias.

Link do documento no drive: https://docs.google.com/document/d/1m-JRNhK9HMJ_JOwBmvTRDMlsQfGa6gnXXDLoM_flG6w/edit

**Comment by cecivieira** [comment]
Criei uma cópia do arquivo dentro da pasta desse ano e revisei.

https://docs.google.com/document/d/1p-xi8uwLucP0LW0-UuLaOWUJ-5M1OMelbcGZ2o_ApXw/edit?usp=sharing

**Comment by lipemorais** [comment]
Pessoal, revisei aqui e fiquei com algumas dúvidas.

Quem vai assinar representando a APyB? Seria alguém da comissão?
Sobre a parte de resolução de conflitos que está descrito como na comarca de Aracaju, não deveria ser alterado para Salvador agora?

**Comment by cecivieira** [comment]
@lipemorais quem assina do lado do evento é a pessoa negociadora. Se você está negociando com a empresa patrocinadora, você assina.

Eu tô me colocando como testemunha da nossa parte.

Sim, a comarca é de Salvador. Acho que isso passou despercebido. Pode alterar

**Comment by kim-soares** [comment]
@cecivieira o texto revisado fica conforme abaixo:

> 10.7. As Partes elegem o foro da Comarca da Cidade de Salvador, Estado da Bahia, como o competente para dirimir quaisquer controvérsias porventura oriundas deste contrato, com renúncia expressa a qualquer outro, por mais privilegiado que seja.

**Comment by kim-soares** [comment]
@cecivieira você pode colocar seus dados no contrato, por favor?

> ASSOCIAÇÃO PYTHON BRASIL
> Nome: 
> CPF: 
> RG:

**Comment by cecivieira** [comment]
@kim-soares Essa representação é de qualquer pessoa da organização que está fazendo a negociação diretamente com a empresa patrocinadora.

Estou me colocando como testemunha, mas as representantes da Associação podem ser você ou Felipe, que estão tratando diretamente com cada empresa.

Como cada um tá pegando uma cliente específica, sugiro que você assine os contratos da sua cliente e Felipe os da dele.

**Comment by kim-soares** [comment]
Entendido @cecivieira !

Me ajuda colocando seus dados lá no arquivo modelo, por favor!

**Comment by cecivieira** [comment]
@kim-soares já coloquei

Também comentei a mesma coisa lá

**Comment by felipythondev** [comment]
Minuta revisada.
