### ISSUE TITLE
Buscar parceria com hotel para hospedagem dos participantes

### ISSUE THREAD

**Issue by Lorenaps** [pythonNordeste/organizacao-pyne-2023#94]
Entrar em contato com hoteis/pousadas, de preferência que sejam em locais mais próximos do evento e 
verificar possibilidade de parceria.
Essa parceria deve se dar da seguinte forma:
- O hotel disponibiliza algum tipo de desconto no valor da hospedagem para os participantes do evento
- O evento oferece a indicação daquele para o seu público alvo que seria em média de 150 a 200 pessoas

Caso um único hotel não acomode todo o público, podemos ter 2 ou mais indicações e ai pra cada um a contrapartida vai ser a  indicação para a quantidade de pessoas que eles podem alocar.

Aqui temos algumas indicações que foram listadas para um outro evento da comunidade aqui em Salvador.
[Lista de hospedagens](https://www.google.com.br/maps/@-12.9908273,-38.4971324,14z/data=!3m1!4b1!4m3!11m2!2sXiVr5eWTTRW7kD_j2vG_CQ!3e3) - Mas pode ficar à vontade que fazer a cotação com outra hospedagem 

**Condições para que a atividade esteja concluída:**
- [ ] O contato pode ser feito por whatsapp ou telefone (um canal mais direto mesmo) da pessoa que estaá fazendo a cotação, mas após as negociações a parceria final deverá ser fechada mediante alguma documentação oficial via email do evento (nordeste@python.org.br)
- [ ] Ter as seguintes informações para divulgação da hospedagem:
    - Nome
    - Endereço
    - Tipo de Quarto
    - Valor já com o desconto
    - Forma que a pessoa participante deve entrar em contato

**Comment by leasampaio** [comment]
Estou em contato com o Ibis do Rio Vermelho https://www.instagram.com/ibisriovermelho/?hl=en

**Comment by leasampaio** [comment]
Retorno do ibis:   tarifas: R$270,00+5%ISS SGL // R$320,00+5%ISS DBL
Prós: É no Rio vermelho e relativamente perto do local do evento, tem café da manhã, é uma rede grande
contra: é caro

**Comment by Lorenaps** [comment]
Oi Lea! Obrigada pela pesquisa!

Esses valores que vc colocou são para qual tipo de quarto e quantas pessoas?

Fiz uma pesquisa aqui no booking e queria sugerir da gente tentar negociar com eles os mesmo preços de junho, considerando a quantidade de pessoas. Vocẽ acha que rola de puxar essa negociação com eles?

![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/9660774/235dd11e-48d0-422e-8ee4-6d4f07abe13e)
![image](https://github.com/pythonNordeste/organizacao-pyne-2023/assets/9660774/34d2aff8-8e91-48ad-98c1-cf3fd6fadb2f)

**Comment by leasampaio** [comment]
@Lorenaps recebi esse retorno: "Infelizmente não conseguimos aplicar essas tarifas, visto que o período cotado é diferente, nossas tarifas são flutuantes de acordo com a demanda do período solicitado."
Vc acha que vale olhar opções mais distantes com valores menores?

**Comment by GomesMarcos** [comment]
Olá, gente!
Sugiro que a hospedagem seja na região do Rio Vermelho por conta de ônibus e atividade noturna (leia-se bares).
Se a pessoa quiser ir de Uber, Barra ou Ondina também são boas opções.

Como fim de Setembro já inicia alta estação, infelizmente é esperado preços maiores.
Essa cotação do Ibis, se for para os 3 dias, está ruim não.

Estou usando o Google pra ver se acho algo mais custo-benefício:
https://www.google.com/maps/search/pousada/@-13.0023678,-38.5199063,14.71z/data=!4m6!2m5!5m3!5m2!1s2023-09-22!2i2!6e3?entry=ttu

https://www.google.com/maps/search/hostel/@-13.013475,-38.5248736,14.75z/data=!4m7!2m6!5m4!5m2!1s2023-09-22!2i2!9i300!6e3?entry=ttu

Filtrei valor máximo de 300 conto o período (22 a 24 /09).

**Comment by cecivieira** [comment]
Negociação realizada com Ibis Rio Vermelho. Todas as participantes do evento tem 12% de desconto em hospedagem no Ibis Rio Vermelho.

A reserva deve ser realizada por e-mail se identificando como participantes:
[H5173-RE@accor.com](mailto:H5173-RE@accor.com)
