### ISSUE TITLE
Tradução do plano de patrocínio

### ISSUE THREAD

**Issue by lipemorais** [pythonNordeste/organizacao-pyne-2023#97]
Tradução do plano de patrocínio para enviar a empresas internacionais.

**Comment by lipemorais** [comment]
Aqui está a versão inicial da tradução que precisa de revisão: https://www.canva.com/design/DAFhOYJ1lb8/RMLXv9WVQi7O2onSGSZ5Dw/edit

@kim-soares @cecivieira  @maribedran pode me ajudar na revisão?

**Comment by maribedran** [comment]
@lipemorais Ajustei uns detalhes pequenos, mas no geral tava ótimo :)
