### ISSUE TITLE
Reunião Thoughtworks

### ISSUE THREAD

**Issue by kim-soares** [pythonNordeste/organizacao-pyne-2023#98]
Pessoal, 

A Gabriela Alves, nosso contato da Thoughworks, solicitou uma reunião no dia **4 de maio, às 10h, via Zoom.**

@lipemorais você consegue participar? Não sei se consigo por conta do trabalho.

**Comment by lipemorais** [comment]
Consigo sim @kim-soares

**Comment by lipemorais** [comment]
A pessoa que está avaliando do lado da TW vai patrocinar uma das 3, AfroPython Conf, Python Nordeste ou Python Brasil.

**Comment by kim-soares** [comment]
@lipemorais eles deram algum retorno?

**Comment by felipythondev** [comment]
Desde a última atualização não deram um retorno.
